### ISSUE TITLE
./train_val_modelnet.sh: line 40: ../../models/cls/pointcnn_cls_modelnet_x2_l4.txt: No such file or directory

### ISSUE THREAD

**Issue by ailib** [yangyanli/PointCNN#1]
您好！出现以上问题，求解决方案

**Comment by burui11087** [comment]
你需要先在pointcnn的上一级目录创建一个model/cls的文件夹  或者去修改sh文件中的../../models/cls的路径

**Comment by burui11087** [comment]
make models/cls directory firstly or modify this path in .sh file
