### ISSUE TITLE
About prepare_multiChannel_seg_data.py

### ISSUE THREAD

**Issue by cl5220418** [yangyanli/PointCNN#10]
There are still bugs in prepare_multiChannel_seg_data.py？

**Comment by burui11087** [comment]
Appreciate your report, I have updated code and README,you can take a look.

Thanks

**Comment by cl5220418** [comment]
There is not categories.txt in '../../data/S3DIS/out_part_rgb/'?

**Comment by burui11087** [comment]
prepare_multiChannel_seg_data.py will generate that file

**Comment by cl5220418** [comment]
Traceback (most recent call last):
  File "../train_val_seg.py", line 267, in <module>
    main()
  File "../train_val_seg.py", line 235, in main
    weights_batch = np.array(label_weights_list)[labels_batch]
IndexError: index 47 is out of bounds for axis 0 with size 13

What's the problem?

**Comment by burui11087** [comment]
I can't replicate your problem. It will helpful if you check your code and outputs. 

If you can provide more details, it's easy for me to solve this issue.

**Comment by cl5220418** [comment]
test_s3dis.sh: 行 2: $'\r': 未找到命令
test_s3dis.sh: 行 8: $'\r': 未找到命令
test_s3dis.sh: 行 16: 未预期的符号 `$'in\r'' 附近有语法错误
'est_s3dis.sh: 行 16: `  case $opt in

**Comment by burui11087** [comment]
@cl5220418 hi

This problem caused by windows/linux characters different >> "\r"(windows)/ "\n"(linux).It has been tackled,please pull new test_s3dis.sh file.

Thanks
