### ISSUE TITLE
如何处理scannet数据集进行分类处理

### ISSUE THREAD

**Issue by HJ-Xu** [yangyanli/PointCNN#100]
请问使用sacnnet进行分类任务的时候是使用poinnet++上下载的scannet压缩包，后缀名.pickle的文件么，我们下载该数据集后，按照readme中的说明使用scannet_split.py生成了6个子文件夹train_data ，train_label ， train_tarns 和val_data，val_label，val_trans，之后再次使用prepare_scannet_cls_data.py处理时会出现各种错误，有时候是找不到文件，有时候是超出索引。
请问我们要如何解决
谢谢！

**Comment by MingChaoSun** [comment]
Hi, @HJ-Xu 

I think you are using an old version. As far as I'm concerned, it's better to pull all files in this repo again~

Thanks,
Mingchao

**Comment by MingChaoSun** [comment]
For ScanNet classification, Please refer to [http://www.scan-net.org/](http://www.scan-net.org/) for downloading ScanNet task data, instead of poinnet++ .pickle files which for segmentation task.

Please follow [README(Scannet classification part)](https://github.com/yangyanli/PointCNN#scannet).

**Comment by HJ-Xu** [comment]
> 对于ScanNet分类，请参考http://www.scan-net.org/下载ScanNet任务数据，而不是用于分段任务的poinnet ++ .pickle文件。
> 
> 请遵循[README（Scannet分类部分）](https://github.com/yangyanli/PointCNN#scannet)。

感谢您的解答，但是在按照
https://github.com/yangyanli/PointCNN#scannet中的python extract_scannet_objs.py -f ../../data/scannet/scannet_dataset_download/data/ -b ../../data/scannet/scannet_dataset_download/benchmark/ -o ../../data/scannet/cls/
python prepare_scannet_cls_data.py -f ../../data/scannet/cls/命令执行会出现FileNotFoundError: [Errno 2] No such file or directory: '../../data/scannet/scannet_dataset_download/benchmark//scannet_trainval.txt'
找不到文件的情况，我已经按照您的文件名严格建立了文件夹，并执行了上面的步骤，请问这是什么情况呢？

**Comment by HJ-Xu** [comment]
> > 对于ScanNet分类，请参考[http://www.scan-net.org/下载ScanNet任务数据，而不是用于分段任务的指针](http://www.scan-net.org/%E4%B8%8B%E8%BD%BDScanNet%E4%BB%BB%E5%8A%A1%E6%95%B0%E6%8D%AE%EF%BC%8C%E8%80%8C%E4%B8%8D%E6%98%AF%E7%94%A8%E4%BA%8E%E5%88%86%E6%AE%B5%E4%BB%BB%E5%8A%A1%E7%9A%84poinnet) ++ .pickle文件。
> > 请[遵循README（Scannet分类部分）](https://github.com/yangyanli/PointCNN#scannet)。
> 
> 感谢您的解答，但是在按照
> [https://github.com/yangyanli/PointCNN#scannet中的python](https://github.com/yangyanli/PointCNN#scannet%E4%B8%AD%E7%9A%84python) extract_scannet_objs.py -f ../../data/scannet/scannet_dataset_download/data/ -b ../ .. / data / scannet / scannet_dataset_download / benchmark / o ../../data/scannet/cls/ 
> python prepare_scannet_cls_data.py -f ../../data/scannet/cls/命令执行会出现FileNotFoundError：[Errno 2 ]没有这样的文件或目录：'../../data/scannet/scannet_dataset_download/benchmark//scannet_trainval.txt' 
> 找不到文件的情况，我已经按照您的文件名严格建立了文件夹，并执行了上面的步骤，请问这是什么情况呢？

并且我也在github上重新下载了代码

**Comment by HJ-Xu** [comment]
> > > 对于ScanNet分类，请参考[http://www.scan-net.org/下载ScanNet任务数据，而不是用于分段任务的指针](http://www.scan-net.org/%E4%B8%8B%E8%BD%BDScanNet%E4%BB%BB%E5%8A%A1%E6%95%B0%E6%8D%AE%EF%BC%8C%E8%80%8C%E4%B8%8D%E6%98%AF%E7%94%A8%E4%BA%8E%E5%88%86%E6%AE%B5%E4%BB%BB%E5%8A%A1%E7%9A%84poinnet) ++ .pickle文件。
> > > 请[遵循README（Scannet分类部分）](https://github.com/yangyanli/PointCNN#scannet)。
> > 
> > 
> > 感谢您的解答，但是在按照
> > [https://github.com/yangyanli/PointCNN#scannet中的python](https://github.com/yangyanli/PointCNN#scannet%E4%B8%AD%E7%9A%84python) extract_scannet_objs.py -f ../../data/scannet/scannet_dataset_download/data/ -b ../ .. / data / scannet / scannet_dataset_download / benchmark / o ../../data/scannet/cls/
> > python prepare_scannet_cls_data.py -f ../../data/scannet/cls/命令执行会出现FileNotFoundError：[Errno 2 ]没有这样的文件或目录：'../../data/scannet/scannet_dataset_download/benchmark//scannet_trainval.txt'
> > 找不到文件的情况，我已经按照您的文件名严格建立了文件夹，并执行了上面的步骤，请问这是什么情况呢？
> 
> 并且我也在github上重新下载了代码


请问这个scannet_trainval.txt里面是什么，https://github.com/ScanNet/ScanNet/tree/master/Tasks/Benchmark这里面没有这个文件

**Comment by MingChaoSun** [comment]
Hi

It looks like they have updated the list file three months ago. If you want to reproduce the results of our experiments， you can use GitHub code history to download [scannet_trainval.txt](https://github.com/ScanNet/ScanNet/blob/1651f8387ca982547c66c91acfd3ee2e75b6ed15/Tasks/Benchmark/scannet_trainval.txt) and [scannet_test.txt](https://github.com/ScanNet/ScanNet/blob/1651f8387ca982547c66c91acfd3ee2e75b6ed15/Tasks/Benchmark/scannet_test.txt), otherwise， use the new list file that matches your dataset is OK. You can change the path in prepare_scannet_cls_data.py.

Thanks,
Mingchao
