### ISSUE TITLE
tensorboard cannot show the results, with error:uncaught TypeError: cannot read property 'getShadePrecissionFormat' of null

### ISSUE THREAD

**Issue by ShirleyBHU** [yangyanli/PointCNN#102]
![image](https://user-images.githubusercontent.com/27609931/48312615-730bdd00-e5ec-11e8-8202-0a47b3220602.png)

**Comment by yangyanli** [comment]
Hi @ShirleyBHU,

It is likely that this is an error not specific to PointCNN. There is better chance if you consider it as an issue of tensorboard.
