### ISSUE TITLE
PointCNN/sampling/tf_sampling_so.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeENS_11StringPieceE

### ISSUE THREAD

**Issue by zhb0920** [yangyanli/PointCNN#103]
when i run  ./test_shapenet.sh -g 0 -x shapenet_x8_2048_fps -l ../../models/seg/pointcnn_seg_shapenet_x8_2048_fps_xxxx/ckpts/iter-xxxxx -r 10,it tell me  tensorflow.python.framework.errors_impl.NotFoundError: /home/hbzhang/tensorflow/PointCNN/sampling/tf_sampling_so.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeENS_11StringPieceE

**Comment by burui11087** [comment]
@Zhanghongbin-github can you train it successfully?

**Comment by HughRunyan** [comment]
Same problem. It has something to do with gcc/g++, I think, but I tried bash tf_sampling_compile.sh with 4.8 and 5 and nothing works. I'm suspicious it's caused by using conda install tensorflow-gpu instead of pip or building from source but not sure

**Comment by lqzhao** [comment]
> 
> 
> when i run ./test_shapenet.sh -g 0 -x shapenet_x8_2048_fps -l ../../models/seg/pointcnn_seg_shapenet_x8_2048_fps_xxxx/ckpts/iter-xxxxx -r 10,it tell me tensorflow.python.framework.errors_impl.NotFoundError: /home/hbzhang/tensorflow/PointCNN/sampling/tf_sampling_so.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeENS_11StringPieceE

Hi, have you addressed this problem?
