### ISSUE TITLE
Visualization of the segmentation results

### ISSUE THREAD

**Issue by RicheyHuang** [yangyanli/PointCNN#104]
Hello, thanks for sharing your great work with us here!  I just downloaded the ScanNet dataset for semantic segmentation task, and I have finished the training and testing. When I wanted to visualize the results, I found that every ply file is just a tiny part of the whole scene. How can I visualize the result of the whole scene? I have no idea which files belong to the same scene. Does every h5 file contain several different scenes?

**Comment by MingChaoSun** [comment]
Hi, @RicheyHuang 

There is a key field called "indices_split_to_full" in the .h5 file which record room_id and in_room_id， you can refer to the [evaluation code (eval_scannet.py)](https://github.com/yangyanli/PointCNN/blob/master/evaluation/eval_scannet.py).  For evaluation, we restore the scene and compute the accuracy， I think you can visualize the whole scene in the last loop of the [eval_scannet.py](https://github.com/yangyanli/PointCNN/blob/master/evaluation/eval_scannet.py).

If you have any questions, please feel free to contact us~

Thanks,
MIngchao

**Comment by RicheyHuang** [comment]
@MingChaoSun Thank you so much~ I'll have a try about this.

**Comment by justbin1123** [comment]
hi @RicheyHuang  i had the same problem. Have you solved this problem with the @MingChaoSun ’s method? u got only one ply for the whole scene ？

**Comment by RicheyHuang** [comment]
Hi! @justbin1123 , I have solved the problem by following the method mentioned above. And what I got was a ply file for the whole scene.

**Comment by justbin1123** [comment]
@RicheyHuang  hi,excuse me again. I didnt find the method that mentioned in the above method in the [evaluation code (eval_scannet.py).   Could u show the code(saving ply data of the whole sence) .Have you changed the code to meet your own needs?

When i ran the eval_scannt.py, i only got the label file.

Looking forward to hearing from you.
Thanks,
Justbin

**Comment by RicheyHuang** [comment]
@justbin1123  Hi, I am not quite sure about the details, but I did change the code in eval_scannet.py. You can just try this:
1. import data_utils
2. from line 92:
for room_id, pts in enumerate(xyz_all):

        label = labels_all[room_id]
        pred = pickle_dict[room_id]["final_label"]

        fileidx = str(room_id) + ".ply"                                                               # added line
        filepath_label_ply = os.path.join(args.datafolder + fileidx)                  # added line
        data_utils.save_ply_property(pts, pred, 21, filepath_label_ply)             # added line

        data_num = pts.shape[0]

        # compute pts acc (ignore label 0 which is scannet unannotated)
        c_accpts = np.sum(np.equal(pred,label))
        c_ignore = np.sum(np.equal(label,0))
        pts_acc_list.append([c_accpts, data_num - c_ignore])

and the output is like this:
![image](https://user-images.githubusercontent.com/21055088/52987167-0bf49480-3435-11e9-9744-0c6929d1b198.png)

wish u luck!

**Comment by justbin1123** [comment]
ok，ill try. eally appreciate it！

**Comment by justbin1123** [comment]
ok，ill try.  Really appreciate it！

**Comment by longmalongma** [comment]
> @justbin1123 Hi, I am not quite sure about the details, but I did change the code in eval_scannet.py. You can just try this:
> 
>     1. import data_utils
> 
>     2. from line 92:
>        for room_id, pts in enumerate(xyz_all):
>        ```
>         label = labels_all[room_id]
>         pred = pickle_dict[room_id]["final_label"]
>        
>         fileidx = str(room_id) + ".ply" # added line
>         filepath_label_ply = os.path.join(args.datafolder + fileidx) # added line
>         data_utils.save_ply_property(pts, pred, 21, filepath_label_ply) # added line
>        
>         data_num = pts.shape[0]
>        
>         # compute pts acc (ignore label 0 which is scannet unannotated)
>         c_accpts = np.sum(np.equal(pred,label))
>         c_ignore = np.sum(np.equal(label,0))
>         pts_acc_list.append([c_accpts, data_num - c_ignore])
>        ```
> 
> 
> and the output is like this:
> ![image](https://user-images.githubusercontent.com/21055088/52987167-0bf49480-3435-11e9-9744-0c6929d1b198.png)
> 
> wish u luck


> @justbin1123 Hi, I am not quite sure about the details, but I did change the code in eval_scannet.py. You can just try this:
> 
>     1. import data_utils
> 
>     2. from line 92:
>        for room_id, pts in enumerate(xyz_all):
>        ```
>         label = labels_all[room_id]
>         pred = pickle_dict[room_id]["final_label"]
>        
>         fileidx = str(room_id) + ".ply" # added line
>         filepath_label_ply = os.path.join(args.datafolder + fileidx) # added line
>         data_utils.save_ply_property(pts, pred, 21, filepath_label_ply) # added line
>        
>         data_num = pts.shape[0]
>        
>         # compute pts acc (ignore label 0 which is scannet unannotated)
>         c_accpts = np.sum(np.equal(pred,label))
>         c_ignore = np.sum(np.equal(label,0))
>         pts_acc_list.append([c_accpts, data_num - c_ignore])
>        ```
> 
> 
> and the output is like this:
> ![image](https://user-images.githubusercontent.com/21055088/52987167-0bf49480-3435-11e9-9744-0c6929d1b198.png)
> 
> wish u luck!

Hello,thanks for your work,I meet same problem on s3dis dataset.after testing,I only generate many part .ply files of whole scene,can you write code about Mergｉｎｇ these files to a whole scene.looking forwarding your reply.

**Comment by Haiyan-Chris-Wang** [comment]
@RicheyHuang 
I meet some problem when I train the segmentation on Scannet, what is "2>&1 &" in the below training script? 
CUDA_VISIBLE_DEVICES=$gpu python3 ../train_val_seg.py -t $train_files -v $val_files -s $models_folder -m pointcnn_seg -x $setting > $models_folder/pointcnn_seg_$setting.txt 2>&1 &

**Comment by spiegelss** [comment]
The ampersand at the end of the line means the shell script runs in the background.  

Note that all output for training is put into the log file of the input (follow the path for the $models_folder/pointcnn_seg_$setting.txt.  There should be text files that log what is going on.  It doesn't directly output the results on the terminal screen.  

You can try and eliminate the ampersand at the end of the line so that it doesn't run in the background.
