### ISSUE TITLE
Random input drop out during traning?

### ISSUE THREAD

**Issue by zeal-github** [yangyanli/PointCNN#105]
In your paper, you mentioned that you sample points to training
![image](https://user-images.githubusercontent.com/40826585/48762629-64a57b80-ece6-11e8-9b13-64b2f057b2bc.png)
But I can only find that you randomly sample 1024 points for classification training but not random drop out.
Since you said in your paper that it's crucial for training, so I want to make sure of it.
Thanks!

**Comment by zeal-github** [comment]
Oh sorry, I have found that what's happening. But I want to make sure again, for each batch_data, the sampling number will be the same(Gaussian distribution), and each point cloud in that batch-data will same point number but different indices. Do I understand it right?

**Comment by yangyanli** [comment]
yes, @zeal-github !
