### ISSUE TITLE
ImportError: No module named sampling in Python 2.7

### ISSUE THREAD

**Issue by jialancong** [yangyanli/PointCNN#115]
Hi, I am able to compile the sampling file but can't use it. I am using python 2.7 and Tensorflow 1.7.0
When I want to import sampling in pointcnn.py, I got the following error :
```
  File "/home/yjm/Project/PointCNN11_24_new/code/pointcnn.py", line 69, in __init__
    from sampling import tf_sampling
ImportError: No module named sampling
```
However, when I compile sampling, I got no error.
My tf_sampling_compile.sh file is : 
```
#/bin/bash
PYTHON=python
nvcc=/usr/local/cuda/bin/nvcc
cudalib=/usr/local/cuda/lib64
tensorflow=/home/yjm/anaconda3/envs/py27_1/lib/python2.7/site-packages/tensorflow/include
TF_INC=$($PYTHON -c 'import tensorflow as tf;print(tf.sysconfig.get_include())')
TF_LIB=$($PYTHON -c 'import tensorflow as tf;print(tf.sysconfig.get_lib())')

$nvcc tf_sampling_g.cu -o tf_sampling_g.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC
g++ -std=c++11 tf_sampling.cpp tf_sampling_g.cu.o -o tf_sampling_so.so -shared -fPIC -I $tensorflow -I$TF_INC/external/nsync/public -L$TF_LIB -ltensorflow_framework -I /usr/local/cuda/include -lcudart -L /usr/local/cuda/lib64/ -O2
```
I would be very grateful if you give me some suggestions ! Thanks!

**Comment by dustindorroh** [comment]
The ‘sampling’ module is in the PointCNN directory make sure you have that
base path added to your PYTHONPATH.

There might be some python 2-3 differences, but I found that they were just
in the new print function syntax and some string formatting when it comes
to floats. But your error is definitely your python path settings.

Cheers,
Dustin

**Comment by jialancong** [comment]
@dustindorroh 
Hi, thanks for your reply.
I copy the code and tested under Python 3.5 and tensorflow 1.7.0, it run successfully T T. 
However, I didn't even modify the sampling file and just change the command in train_val_modelnet.sh from  `python3 ../train_val_cls.py` to `python ../train_val_cls.py`.

**Comment by jialancong** [comment]
@dustindorroh 
Thank you for your reply! I solved this by adding the sampling folder path under site-packages of python 2.7. Btw, I copied the project and tested under python 3.5 and tensorflow 1.7.0, I run successfully. However, I don't even change the sampling file. Only the python version is different.

Therefore, I am assuming, this error arises from the fact that the sampling file has not been compiled properly under python 2.7.

**Comment by yangyanli** [comment]
Many thanks for your reply, @dustindorroh !

**Comment by xiaomao19970819** [comment]
你

**Comment by xiaomao19970819** [comment]
> @dustindorroh
> 感谢您的回复！我通过将采样文件夹路径添加到python 2.7的site-packages来解决这个问题。顺便说一句，我复制了项目并在python 3.5和tensorflow 1.7.0下测试，我运行成功。但是，我甚至没有更改采样文件。只有python版本不同。
> 
> 因此，我假设，这个错误源于在python 2.7下未正确编译采样文件的事实。
> 
> 干杯，
> 嘉兰聪

hello，Can you show me more details about the configuration?I have the same problem，thank you

**Comment by jialancong** [comment]
> > @dustindorroh
> > 感谢您的回复！我通过将采样文件夹路径添加到python 2.7的site-packages来解决这个问题。顺便说一句，我复制了项目并在python 3.5和tensorflow 1.7.0下测试，我运行成功。但是，我甚至没有更改采样文件。只有python版本不同。
> > 因此，我假设，这个错误源于在python 2.7下未正确编译采样文件的事实。
> > 干杯，
> > 嘉兰聪
> 
> hello，Can you show me more details about the configuration?I have the same problem，thank you

sure,
```
#/bin/bash
PYTHON=python
nvcc=/usr/local/cuda/bin/nvcc
cudalib=/usr/local/cuda/lib64
tensorflow=/home/yjm/anaconda3/envs/py27_1/lib/python2.7/site-packages/tensorflow/include
TF_INC=$($PYTHON -c 'import tensorflow as tf;print(tf.sysconfig.get_include())')
TF_LIB=$($PYTHON -c 'import tensorflow as tf;print(tf.sysconfig.get_lib())')

$nvcc tf_sampling_pcnn_g.cu -o tf_sampling_pcnn_g.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC
g++ -std=c++11 tf_sampling_pcnn.cpp tf_sampling_pcnn_g.cu.o -o tf_sampling_pcnn_so.so -shared -fPIC -I $tensorflow -I$TF_INC/external/nsync/public -L$TF_LIB -ltensorflow_framework -I /usr/local/cuda/include -lcudart -L /usr/local/cuda/lib64/ -O2
```

**Comment by xiaomao19970819** [comment]
thanks for your answer
I would like to consult you about the code of semantic3D data set。
models_folder =“../../ models / seg /” 
train_files =“../../ data / semantic3d / out_part / train_data_files.txt” 
val_files =“../../ data / semantic3d / out_part / val_data_files.txt”

I saw the above code at the beginning of  train_val_semantic3d.sh , but the following error occurred when I was running it.I found that there was no " out_part " folder

I also want to know how long you are running  ./ train_val_semantic3d.sh ?

**Comment by jialancong** [comment]
> thanks for your answer
> I would like to consult you about the code of semantic3D data set。
> models_folder =“../../ models / seg /”
> train_files =“../../ data / semantic3d / out_part / train_data_files.txt”
> val_files =“../../ data / semantic3d / out_part / val_data_files.txt”
> 
> I saw the above code at the beginning of train_val_semantic3d.sh , but the following error occurred when I was running it.I found that there was no " out_part " folder
> 
> I also want to know how long you are running ./ train_val_semantic3d.sh ?

Sorry, I haven't run ./ train_val_semantic3d.sh. I just tested the modelnet and shapenet dataset.
