### ISSUE TITLE
S3DIS point number

### ISSUE THREAD

**Issue by CZ-Wu** [yangyanli/PointCNN#119]
请问s3dis分割你们用了多少个点的？好像s3dis_x8_2048_fps.py并没有点数的设置，你们的点数是是在生成数据集的时候确定的吗？你们是用8192个点的吗？

**Comment by CZ-Wu** [comment]
我看到了，不好意思。你们定义placeholder的时候用的是生成数据时候的点数，后面还有一个采样的过程，为什么不在数据预处理的时候把采样也做了呢？

**Comment by yangyanli** [comment]
The sampling is applied online such that the data used for training is different from different epochs, i.e., better data augmentation.
