### ISSUE TITLE
tu_berlin cls missing train&val list

### ISSUE THREAD

**Issue by deepearthgo** [yangyanli/PointCNN#12]
Great Work. I ran most experiments. Smooth

One experiment for tu_berlin classification missing train&val file list after raw data conversion.

**Comment by burui11087** [comment]
@deepearthgo Hi

Thanks for your  attention.

I added two commands(cat) about tu_berlin in README. You can generate train&val file by using that.

**Comment by deepearthgo** [comment]
Great! Thanks Very Much.

**Comment by zxy14120448** [comment]
> Great Work. I ran most experiments. Smooth
> 
> One experiment for tu_berlin classification missing train&val file list after raw data conversion.

Hello， I have some problem about training tu_berlin. can I add your wechat and you can send your wechat number to my mail:zhangyuexiang90@gmail.com. Thank you very much.
