### ISSUE TITLE
你好，我在尝试用你们的代码训练semantic 3d时遇到了问题，希望你们可以解答一下

### ISSUE THREAD

**Issue by xiaomao19970819** [yangyanli/PointCNN#120]
models_folder="../../models/seg/"
train_files="../../data/semantic3d/out_part/train_data_files.txt"
val_files="../../data/semantic3d/out_part/val_data_files.txt"

您好，我看到在你们的train_val_semantic3d.sh开头部分中有以上的代码，但是我运行时候出现了以下错误：
IOError: [Errno 2] No such file or directory: '../../data/semantic3d/out_part/train_data_files.txt'
请问代码中这个文件夹是什么时候生成的呢？

在你们首页给出的训练运行semantic3d数据集的指令中，其中一条是：
python3 prepare_semantic3d_data.py
我怀疑这一条是不是缺少了一些参数？希望您可以帮我解答，非常感谢。

**Comment by burui11087** [comment]
Hi @xiaomao19970819 

Please update your local repo, we support train/val/test data generate respectively.

Thanks！

**Comment by ywyue** [comment]
Hi, thanks for your great work! 
I meet the same problem with @xiaomao19970819 . 
I ran the command:
bash download_semantic3d.sh, then there did generate train/val/test data respectively. However, there was no folder named 'out_part' , which resulted an error when I ran the command: 
./train_val_semantic3d.sh -g 0 -x semantic3d_x4_2048_fps. 
In the 'pointcnn_seg_semantic3d_x4_2048_fps.txt', it reported 'No such file or directory: '../../data/semantic3d/out_part/train_data_files.txt'.
Could you help me? Thank you!

**Comment by ClosedOn** [comment]
Hi, thanks for your great work!
I meet the same problem with @xiaomao19970819 .

**Comment by ClosedOn** [comment]
Hi, thanks for your great work!
I meet the same problem with @xiaomao19970819 .
No such file or directory: '../../data/semantic3d/out_part/train_data_files.txt'
Have you solved this problem?
