### ISSUE TITLE
Test of Semantic3D dataset

### ISSUE THREAD

**Issue by wliebtzy** [yangyanli/PointCNN#121]
Hi,
I have been successful to train the model with Semantic3D dataset. Then I try to get the test result, but there are all classes as 1 in the files after using the /evaluation/semantic3d_merge.py. Is there problem in the test process or the merge process?

**Comment by xiaomao19970819** [comment]
Hello, I have been testing this test set recently, and I found that the code part needs to be modified. I encountered some problems. Could you please upload a copy of your modified code?I want to refer to it. In addition, my sampling module cannot be imported

**Comment by windtries** [comment]
@wliebtzy I meet the same problems with you,may I know if you have solved it?
