### ISSUE TITLE
evaluation metric

### ISSUE THREAD

**Issue by CZ-Wu** [yangyanli/PointCNN#123]
I find that you use precision as the evaluation metric, but other works (e.g. pointnet, dgcnn) use accuracy as the evaluation metric. Could you tell me why don't you use accuracy?

**Comment by MingChaoSun** [comment]
Hi，

We used  tf.metrics.precision_at_k（k=1） in earlier versions, when k = 1, it is equivalent to accuracy. Then we found that using tf.metrics.accuracy would be faster, so modified it and used up to now.

BTW, tf.metrics.precision is NOT equivalent to accuracy, the input labels and predictions will be cast to bool (True ~ Positive samples / False ~ Negative samples), and then compute the true_positives(TP) and false_positives(FP), finally precision = TP/(TP + FP).

Thanks,
Mingchao
