### ISSUE TITLE
issue about the parameters of segmentation task for scannet dataset

### ISSUE THREAD

**Issue by What-ifs** [yangyanli/PointCNN#127]
Hi, I got a problem that if the parameters of segmentation task for scannet dataset is not correct. The result calculated by me is 11.5M but 4.4M in your paper(NIPS 2018).

**Comment by burui11087** [comment]
we get 4.4M on shapenet task. As you can see, we will update the config files immediately when we find a better hyper parameters. If you want to use out time version, you can check file history in github

Thanks

**Comment by What-ifs** [comment]
thank you for your reply!

**Comment by Houssembenmid** [comment]
I wonder how can you calculate the trainable poarameters
