### ISSUE TITLE
In "more implementation", you add unofficial pytorch implementation

### ISSUE THREAD

**Issue by jw-j** [yangyanli/PointCNN#137]
Did you verify this  unofficial pytorch implementation? I have try to run it, but failed to get a reasonal result. That repo even does not provide a test script.

**Comment by jxqhhh** [comment]
> Did you verify this unofficial pytorch implementation? I have try to run it, but failed to get a reasonal result. That repo even does not provide a test script.

Try this one: https://github.com/jxqhhh/PytorchPointCNN
