### ISSUE TITLE
Why need to multiply extra coefficient in this formula

### ISSUE THREAD

**Issue by LZDSJTU** [yangyanli/PointCNN#14]
line 120 in semantic3d_split.py, why need to multiply nvox[0] and nvox[1]?
line120: vidx = vidx[:, 0] + vidx[:, 1] * nvox[0] + vidx[:, 2] * nvox[0] * nvox[1]

I do not understand the downsample method. Does this method have a name or some reference?

**Comment by MingChaoSun** [comment]
We divide the space into 5cm*5cm*5cm(res = 0.05) grid, and random pick a point for each voxel. More uniform point cloud will be produced by this sampling method, at the same time, we can get the mapping between the original point cloud and the sampled point cloud through the grid.
