### ISSUE TITLE
How is the inference FLOPs computed

### ISSUE THREAD

**Issue by Yochengliu** [yangyanli/PointCNN#141]
The inference FLOPs in PointNet paper is 440M/sample,  but yours is 14.70B/16sample, both are with 1024 input points. It seems these two FLOPs are actually not equal, right?

**Comment by burui11087** [comment]
Hi @Yochengliu 

The FLOPs reported in PointNet is _float op per SAMPLE_ and didn't include BN etc. op. Our FLOPs means _floating point operations_, calculated by Tensorflow API `opts = tf.profiler.ProfileOptionBuilder.float_operation()` ,it will calculate all op registered in Tensorflow.

Thanks.

**Comment by Yochengliu** [comment]
Ok, thanks.
