### ISSUE TITLE
Validation labels are missing in Semantic3D

### ISSUE THREAD

**Issue by dmitrykudinov** [yangyanli/PointCNN#142]
The labels are stored in single 7z file for both Val and Train sets. Please extract the labels in both places, as currently they are extracted into Train folder only:
https://github.com/yangyanli/PointCNN/blob/master/data_conversions/download_semantic3d.sh#L16

**Comment by burui11087** [comment]
Hi @dmitrykudinov 

Thanks for you suggestion, we will revisit our code and refactor it for more convenient using when we have spare time.

Thanks again.

**Comment by longmalongma** [comment]
> d in single 7z file for both Val and Train sets.

hi,have you implement visualization of segmentation on semantic3d dataset?
