### ISSUE TITLE
Has anyone successfully compiled tf_sampling_so.so on windows?

### ISSUE THREAD

**Issue by alicexja** [yangyanli/PointCNN#144]
I'm trying to reproduce semantic segmentation results on shapenet with pointcnn. My working environment is Windows7. I've successfully compiled tf_sampling_g.cu.o, then I tried to compile tf_sampling_so.so. I used mingw to run g++ commands below (from tf_sampling_compile.sh ):

> g++ -std=c++11 tf_sampling.cpp tf_sampling_g.cu.o -o tf_sampling_so.so -shared -fPIC -L "C:/Program Files/Anaconda3/envs/env/lib/site-packages/tensorflow" -l tensorflow_framework -I "C:/Program Files/Anaconda3/envs/env/lib/site-packages/tensorflow/include/external/nsync/public/" -I "C:/Program Files/Anaconda3/envs/env/lib/site-packages/tensorflow/include" -I "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include" -lcudart -L "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/" -O2 -D_GLIBCXX_USE_CXX11_ABI=0

but get error like: 

> cpu_info.h:20:20: fatal error: intrin.h: No such file or directory
> #include <intrin.h>
> ^
> compilation terminated.

Has anybody successfully compiled tf_sampling_so.so on Windows? Many thanks for your help.

**Comment by burui11087** [comment]
Hi @alicexja 

I think it's better to use linux to reproduce expriments, it can avoid a lot of  potential problems.

Thanks
