### ISSUE TITLE
modelnet classification

### ISSUE THREAD

**Issue by DanMurtin** [yangyanli/PointCNN#146]
Hello!
I was trying to run the modelnet classification, but after running 
`./train_val_modelnet.sh -g 0 -x modelnet_x3_l4`
I get error that . is not recognized as command, so i tried running just the .sh script
`train_val_modelnet.sh -g 0 -x modelnet_x3_l4`
but it asked for a program with which it should open it, I used Python (installed 3.6 version) and it shows errors. First it shows 

> gpu=
>        ^
> SyntaxError: invalid syntax

which is basically first line of code, and if I hid the line (commented), the next line would be error.
What am I doing wrong?

Thanks in advance!

**Comment by burui11087** [comment]
Hi @DanMurtin 

Please try following command
`sh train_val_modelnet.sh -g 0 -x modelnet_x3_l4`

Thanks

**Comment by DanMurtin** [comment]
Hello, 
Thank you for the quick reply.

I have tried it and it does not recognize  sh as a command. To be clear, I have activated virtual enviroment, and I am located in the pointcnn_cls folder when running the cmd command. 

Thank you

**Comment by burui11087** [comment]
Are you using Windows?

**Comment by DanMurtin** [comment]
Yes

**Comment by burui11087** [comment]
Hi @DanMurtin 

We have test our code on Windows, I think it's better to change to linux platform.

Thanks
