### ISSUE TITLE
About h5 files for Semantic3d Segmentation

### ISSUE THREAD

**Issue by atikenes** [yangyanli/PointCNN#147]
Hi,
I tried to segment point cloud using semantic3d dataset. But in "./train_val_semantic3d.sh -g 0 -x semantic3d_x4_2048_fps" step, I gave a error like in the image below

![eroror2](https://user-images.githubusercontent.com/32953363/53549896-79e04080-3b46-11e9-9fb0-bc072765ad29.png)

And on the terminal scene, "Train/Val with setting semantic3d_x4_2048_fps on GPU 0!"
was written only. How can I solve this problem?

Thanks for your answers

**Comment by burui11087** [comment]
Hi @atikenes 

I update code and please rerun` python3 prepare_s3dis_filelists.py` to generate a new filelists. Then it will be ok to run train/val.

Thanks.
