### ISSUE TITLE
ModelNet40 Accuracy

### ISSUE THREAD

**Issue by rruixxu** [yangyanli/PointCNN#149]
Hi, 
I previously saw the former version of your paper submitted to arXive. In that paper, the accuracy on ModelNet40 is 91.7%. However, the accuracy becomes 92.2% and 92.5% for unaligned and pre-aligned settings respectively, which is a big improvement. So, could you explain what upgrades did you do in your new version so that around 0.5% improvement was achieved? Moreover, is 91.7%  in unaligned or pre-aligned setting?
Another question: considering 5000 points and normal vectors are available, why don't you do experiments with 5000 points and normal vectors? In that case, it will convince people better.

**Comment by rruixxu** [comment]
Can the code recover accuracy in the new version like 92.2% or 92.5%?

**Comment by burui11087** [comment]
Using our default config, you can get the similar results.

Thanks

**Comment by yangyanli** [comment]
@rruixxu 91.7% in an earlier version is on un-aligned setting. The improvement is mainly due to the implementation in the MLP implementation (normalization, fully connected -> col/row connected, etc.) of X-transformation.
