### ISSUE TITLE
problems when training modelnet 

### ISSUE THREAD

**Issue by botaichang** [yangyanli/PointCNN#15]
when i train the modelnet with tensorflow 1.4, The process halt on and seems not running, should it read h5 file slowly or really does not run, but it has allocate GPU memory already?  Message halt on like these as following: 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)

**Comment by burui11087** [comment]
@botaichang Hi

h5 file need about several minutes to load. You can check the status by use "htop"/"top" command and find that thread. 

But you said your GPU has been allocated, I think your data has been load. You can get more information in models/cls/*/log.txt.

Thanks

**Comment by botaichang** [comment]
@burui11087 Thank you. I find the problem. And I also want to ask how should i visualize the h5 files if I wanna to see the 3d objects?

**Comment by yangyanli** [comment]
Hi @botaichang,

We have some functions in data_utils.py for dumping data into *.ply files, which can be easily visualized by 3D point cloud viewers, such as MeshLab.
