### ISSUE TITLE
could not run the code!!

### ISSUE THREAD

**Issue by zhengkai17** [yangyanli/PointCNN#151]
python3 ./prepare_mnist_data.py -f ../../data/mnist   

(tensor16) zhengkai@zhengkai-ThinkStation-P920:~/PointCNN/data_conversions$ python3 ./prepare_mnist_data.py -f /home/zhengkai/data/mnist
Traceback (most recent call last):
  File "./prepare_mnist_data.py", line 14, in <module>
    from mnist import MNIST
ImportError: cannot import name 'MNIST'        
it seems that the Mnist data downloaded before could not work ,please help me ,thank you.

**Comment by rruixxu** [comment]
> python3 ./prepare_mnist_data.py -f ../../data/mnist
> 
> (tensor16) zhengkai@zhengkai-ThinkStation-P920:~/PointCNN/data_conversions$ python3 ./prepare_mnist_data.py -f /home/zhengkai/data/mnist
> Traceback (most recent call last):
> File "./prepare_mnist_data.py", line 14, in
> from mnist import MNIST
> ImportError: cannot import name 'MNIST'
> it seems that the Mnist data downloaded before could not work ,please help me ,thank you.
Seems no class named MNIST. I cannot find that MNIST class as well.

**Comment by burui11087** [comment]
Hi all:

Please refer to this [link](https://stackoverflow.com/questions/42755078/importerror-cannot-import-name-mnist). That may cause by Third-party libraries.

Thanks.

**Comment by zhengkai17** [comment]
Hi,Thx
Traceback (most recent call last):
  File "../train_val_cls.py", line 344, in <module>
    main()
  File "../train_val_cls.py", line 72, in main
    data_train, label_train, data_val, label_val = setting.load_fn(args.path, args.path_val)
  File "/home/zhengkai/PointCNN/data_utils.py", line 139, in load_cls_train_val
    data_train, label_train = grouped_shuffle(load_cls(filelist))
  File "/home/zhengkai/PointCNN/data_utils.py", line 134, in load_cls
    return (np.concatenate(points, axis=0),
ValueError: need at least one array to concatenate  

another problem when I try to train on Mnist data set, could you explain it? many thanks.

**Comment by burui11087** [comment]
@zhengkai17 Please check your data path
