### ISSUE TITLE
sample number

### ISSUE THREAD

**Issue by rruixxu** [yangyanli/PointCNN#153]
Hi, 
In your NIPS paper, you claim that the number of points for ModelNET 40 training is sampled from _N(1024,_ 128**2). Bust I found a fatal bug in your tensorflow code. The sample_num_variance and sample_num_clip are set to (1//8) and (1//4) respectively, which are two int zeros. In that setting, the number of points for training is still 1024.
I wish you could revise them.
Thanks.

**Comment by burui11087** [comment]
Hi @rruixxu 
Thanks for your report, following this line https://github.com/yangyanli/PointCNN/blob/e40e15a61fb25313f18264548d7b21f649986f60/train_val_cls.py#L312 
1024 * 1 // 8 equal to 128, not 0. Please notice operator precedence.

Thanks.
