### ISSUE TITLE
Variable name or other graph key is missing from the checkpoint of part segmentation.

### ISSUE THREAD

**Issue by CZ-Wu** [yangyanli/PointCNN#157]
When I want to test your pretrained model of part segmentation, it shows me that 'Key xdconv_5_X_0/kernel not found in checkpoint'. It seems that your checkpoint does not match the model defined in your codes.

**Comment by burui11087** [comment]
Hi @CZ-Wu 

Sorry about that. It's almost 1 year passed and the uploaded model is only what I can find, you can delete `(16, 6, 3, 3),` in https://github.com/yangyanli/PointCNN/blob/8822c23822e99c305627005e2fbad5bba64ffa87/pointcnn_seg/shapenet_x8_2048_fps.py#L48, and you can load pretrained model successfully.

Thanks.
