### ISSUE TITLE
About Semantic3D Dataset

### ISSUE THREAD

**Issue by scsc-yss** [yangyanli/PointCNN#161]
Hello,
Thank you for your good paper and source code. 
Now I have a question about how to work on Semantic3D dataset. In your code, the input of the dataset dim is 7, and I think it means you have used the RGB information for segmentation. So how about the result of it? I have not seen the result in your paper.
Also I want to use the pretrained network to test on the other outdoor point cloud dataset, which dose not have RGB information. Could you tell me how to do it? I mean if the RGB information is necessary for train pointcnn, and if I do not have it, the result would be bad?  
Thanks.

**Comment by hamzatrq** [comment]
Hi @burui11087 can you please respond to this?

**Comment by sayakgis** [comment]
The training could happen on 3 dimension also, using semantic3d_x4_2048_fps.py and setting

> data_dim = 3
> use_extra_features = False

The train_val_seg.py has option written to take 3 dimension as well.
_if setting.data_dim > 3:
        points_sampled, features_sampled = tf.split(pts_fts_sampled,
                                                    [3, setting.data_dim - 3],
                                                    axis=-1,
                                                    name='split_points_features')_

request @burui11087 to share on transfer learning point using pretrained model

**Comment by Houssembenmid** [comment]
hi I have tried to change the num of dimention to 7 but this error came up when doing the training (ValueError: Dimensions must be equal, but are 7 and 3 for 'points_xformed' (op: 'BatchMatMul') with input shapes: [?,?,7], [?,3,3].) 

do I need to make some changes in the train.py? i am working on semantic 3d by the way
