### ISSUE TITLE
About the loss

### ISSUE THREAD

**Issue by What-ifs** [yangyanli/PointCNN#163]
Hi,
I have noticed that in your NIPS paper you prepare the S3DIS and ScanNet dataset by slice room into 1.5m by 1.5m blocks with 0.3m padding on each side, and themselves are not linked to loss in the training phase, nor used for prediction in the testing phase. but I am not find something refer to it, am I wrong? can you tell me some points?

**Comment by burui11087** [comment]
Hi @What-ifs 

0.3m padding on each side just offer neighborhood information for the edge point in 1.5m by 1.5m blocks, it doesn't involved in the loss calculation. So loss determined by the point cloud fall on 1.5m*1.5m blocks.

**Comment by TerryLiu007** [comment]
Hi,

I can not find any definition of 0.3m padding in the published code. From what I understand, during training you dynamically sample certain points with a variance 1 // 8. But the input points are all within 1.5m x 1.5m block, and the indices are gathered within the block also. Am I missing anything?
