### ISSUE TITLE
repeat_num for S3DIS

### ISSUE THREAD

**Issue by kentangSJTU** [yangyanli/PointCNN#164]
Dear authors,

Hi! Thanks for your great work. I am trying to use your code for the S3DIS dataset recently. I notice that in [test_general_seg.py] there's a "repeat_num" flag. It is set to 1 by default. According to my experience on part segmentation, typically repeat_num > 1 will produce better results because of ensembling effects (actually you used repeat_num = 10 for partseg). I would like to know whether repeat_num > 1 is used for your reported S3DIS results (mIOU=65.39% across 6 areas and mIOU=57.26% for area 5). Thanks for your reply~

Best,
Ken

**Comment by burui11087** [comment]
Hi @kentangSJTU 

You can get the answer from our readme, we used repeat_num=10 following SSCN from Facebook on ShapeNet segmentation task for fair, repeat_num=4 on others.
However, after our observation, repeat_num doesn't have significant influences on S3DIS and ScanNet.

Thanks.

**Comment by kentangSJTU** [comment]
Hi Rui,

Thank you for your answer ~

Best wishes,
Ken

**Comment by longmalongma** [comment]
> Dear authors,
> 
> Hi! Thanks for your great work. I am trying to use your code for the S3DIS dataset recently. I notice that in [test_general_seg.py] there's a "repeat_num" flag. It is set to 1 by default. According to my experience on part segmentation, typically repeat_num > 1 will produce better results because of ensembling effects (actually you used repeat_num = 10 for partseg). I would like to know whether repeat_num > 1 is used for your reported S3DIS results (mIOU=65.39% across 6 areas and mIOU=57.26% for area 5). Thanks for your reply~
> 
> Best,
> Ken

Hello,I am also trying  to do semantic segmentation on s3dis dataset.after I run eval_s3dis.py,I can not visualize the experiments results of whole scene.do you meet this problem?
