### ISSUE TITLE
Time usage for training/validation.

### ISSUE THREAD

**Issue by SUZhaoyu** [yangyanli/PointCNN#167]
Hi, I'd want to know the time usage **0.031/0.012** you reported in the paper:

> As shown in Table 6, we summarize our running statistics based with the model for classification with batch size 16, 1024 input points on nVidia Tesla P100 GPU, in comparison with several other methods. PointCNN achieves 0.031/0.012 second per batch for training/inference on this setting. 
 
is measured for a mini-batch size of 16 or 1/16 iteration within a mini-batch? I tried to reproduce your code based on a 2080-ti with TF 1.13 and CUDA 10.0, and the time usage in training phase was **0.34s** for a mini-batch (ModelNet40 using config file [modelnet_x3_l4_yxz.py](https://github.com/yangyanli/PointCNN/blob/master/pointcnn_cls/modelnet_x3_l4_yxz.py) ), which means **0.0213s** per 1/16 iteration within a mini-batch. Seems that the time usage you reported in the paper is calculated based on the latter criteria right?

**Comment by burui11087** [comment]
Hi @SUZhaoyu 

Thanks for your interest in our work. we get the time usage 0.031/0.012 second by using this file([modelnet_x3_l4.py](https://github.com/yangyanli/PointCNN/blob/master/pointcnn_cls/modelnet_x3_l4.py)) and change following line to 16. https://github.com/yangyanli/PointCNN/blob/01d1b65adce95a8bc98be3c28f8a63472f5131c1/pointcnn_cls/modelnet_x3_l4.py#L20

BTW, our environment is TF 1.5.1, CUDA 8.0 on DGX P100.

Thanks!

**Comment by SUZhaoyu** [comment]
Thanks @burui11087, I noticed that I did not change the batch size and used the initial 128 by default. I changed the batch size to 16 and the time usage now is 0.06s/training batch.
