### ISSUE TITLE
Segmentation-ScanNet -Permission denied

### ISSUE THREAD

**Issue by Timaces** [yangyanli/PointCNN#169]
I have some questions when I train the Segmentation-ScanNet
l@l-THUNDEROBOT-PC:~/Desktop/PointCNN-master/pointcnn_seg$ ./train_val_scannet.sh -g 0 -x scannet_x8_2048_k8_fps 
bash: ./train_val_scannet.sh: Permission denied

who can help me ?thanks!

**Comment by yangyanli** [comment]
Google something like "permission denied when running .sh"
