### ISSUE TITLE
Feed different group of points into independent PointCNNs parallelly

### ISSUE THREAD

**Issue by wangjksjtu** [yangyanli/PointCNN#17]
Thanks for your excellent work! I have noticed it extraordinary performance in sparse points (32 -> 80%+ in ModelNet40). Recently, I am trying to utilize it to detect objects. However, after grouping the raw points, I need to feed every group of points into en independent PointCNN. However, I had trouble in doing so. 

This is because the the input is (Batch_size x Group_num x Points_of_Each_Group x XYZ), but the input of PointCNN is (Batch_size x Points_num x XYZ). More specifically, my input is (128 x 64 x 64 x 3) whose dimension is 4, but the dimension of PointCNN's expected input is 3. 

I don't want to feed one group one by one, for it is inefficient so I am wondering whether the code of PointCNN (pointcnn.py for example) could be used in parallel computing of different group. I think it is plausible only by changing a few lines of code.  Really hope you can help me solve this problem.

Thank you in advance !!

**Comment by yangyanli** [comment]
Hi @wangjksjtu,

Thanks for your interest in PointCNN!

If I understand right, what you want to do can be easily achieved by reshaping your input 4D tensor into  3D tensor with shape (Batch_size x Group_num, Points_of_Each_Group, XYZ), then passing it through PointCNN, and finally reshaping the results from (Batch_size x Group_num, result) into (Batch_size, Group_num, result).

Is this what you want?

**Comment by wangjksjtu** [comment]
Thanks for your timely reply! I forgot to think it in this way. I believe that in this way my problem will be solved properly.
