### ISSUE TITLE
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by xyjmdr** [yangyanli/PointCNN#170]
I find when I set save_ply_fn = True in modelnet_x3_l4.py then train_val_cls.py indicates error with  TypeError: 'bool' object is not callable. I found the error is line92: setting.save_ply_fn(data_sample, folder), and I cannot found this function save_ply_fn.

**Comment by burui11087** [comment]
Hi @xyjmdr 
Please reference this line https://github.com/yangyanli/PointCNN/blob/01d1b65adce95a8bc98be3c28f8a63472f5131c1/pointcnn_cls/quick_draw_full_x2_l6.py#L28
