### ISSUE TITLE
problem of dataset preparing

### ISSUE THREAD

**Issue by HannahXu** [yangyanli/PointCNN#18]
i have one or some CAD image(pcl, ply, obj, pcd....) of objects in real word around me ,how can I transfer it to h5 file ? then input this h5 file to pointCNN, thanks!

**Comment by yangyanli** [comment]
Hi @HannahXu ,

Point cloud can be generated from mesh files from virtual scanning (e.g., by PCL library), or sampling from the mesh faces (e.g., https://chrischoy.github.io/research/barycentric-coordinate-for-mesh-sampling/), or from level set (e.g., by OpenVDB).

**Comment by HannahXu** [comment]
thanks,but i have had some point cloud image,what i wanna know is how i can generate  h5 file with these point cloud image. Because your method is for standard dataset

**Comment by yangyanli** [comment]
In this case, you can take a look at how we convert MNIST into point cloud in h5 files.
