### ISSUE TITLE
how to make predictions

### ISSUE THREAD

**Issue by Paliking** [yangyanli/PointCNN#184]
Hi,
I trained a classification model for ModelNet40 based on your code.
How can I make predictions now?

I can load the model as:

```
tf.reset_default_graph()
with tf.Session() as sess:
    saver = tf.train.import_meta_graph(model+'.meta')
    saver.restore(sess, model)
```
What is next?

thank you

**Comment by burui11087** [comment]
Hi，
Please reference validation block code 
https://github.com/yangyanli/PointCNN/blob/7d0af994718dd49c66faf21c03c964613e8bdc6f/train_val_cls.py#L262
Thanks

**Comment by Paliking** [comment]
thank you @burui11087 I figured it out.
thx for the project

**Comment by niallomahony93** [comment]
@Paliking Can you share your code since you figured it out please?, I am struggling to run this and use in my application.
