### ISSUE TITLE
How to train my own dataset?

### ISSUE THREAD

**Issue by HuiminYang** [yangyanli/PointCNN#187]
I want to use PointCNN to train my point cloud dataset, how can i modify the code?
Current situation: I have debugged the original author's modelnet classification network code, generated my own h5 file, changed the number of categories to my own category number, and changed the dataset path to my own dataset path. However, the program run incorrectly., I don't know why, I feel that there are some changes, I didn't find it, I hope you can give me some advice.

**Comment by burui11087** [comment]
Hi @HuiminYang 
Could you upload the information when network crashed? It will better for us to solve your issue
Thanks

**Comment by burui11087** [comment]
@HuiminYang 
I will close this issue because it has been solved by we chatted on other social application.
Thanks!
