### ISSUE TITLE
can you write a simple tutorial for training with custom data ? 

### ISSUE THREAD

**Issue by jediofgever** [yangyanli/PointCNN#202]
Hello , thanks for great open source contribution, I would like to try out the network on my custom artificially created data. I only see guides that go through existing datasets and there is not many resources to guide for custom data training,  it would be great if you could provide some generic script or steps that explains process , 
Thank you very much for your time

**Comment by burui11087** [comment]
1.Check your task type. Classification or Segmentaion
2.find a public dataset which similar with your own created data
3.keep same file structure with that public dataset
4.run response prepare script, such as prepare_cifar10_data.py

Thanks
