### ISSUE TITLE
Issues with semantic3d_merge.py

### ISSUE THREAD

**Issue by ninasinger** [yangyanli/PointCNN#208]
I am trying to visualize the labels returned in the "results/*.txt" from the semantic3d_merge.py. However, it seems that the labels do not correspond to the original order of the txt files used as the input to "data_conversions/prepare_semantic3d_data.py" . Can you give me some information about how to pair the final labels with their original x,y,z coordinates?

**Comment by Tojens** [comment]
Having the same issue - did you manage to figure this out?
