### ISSUE TITLE
How can I train model with my own pcd data?

### ISSUE THREAD

**Issue by kevin-steiner** [yangyanli/PointCNN#215]
I want to do a classification work on 3D model, but my own data are .pcd file. How can I train them using Point CNN. Thank you!

**Comment by kevin-steiner** [comment]
When I try to run the code using modelnet with  **./train_val_modelnet.sh -g 0 -x modelnet_x3_l4** in ubuntu 18.04,python 3.8.2,tensorflow 2.1.0, it ended immediately and the log is:
![1585661971(1)](https://user-images.githubusercontent.com/29630934/78032814-28813100-7398-11ea-9d10-3514b1b5d611.jpg)

**Comment by SERPENT-H** [comment]
maybe you should convert pcd data to hdf5 data

**Comment by kevin-steiner** [comment]
> maybe you should convert pcd data to hdf5 data

Thank you for you reply. It is a good idea but I think converting is not easy beacause I don't find a way in PCL. Do you have any idea of how converting it? Thank you again!

**Comment by SERPENT-H** [comment]
> maybe you should convert pcd data to hdf5 data
> 
> Thank you for you reply. It is a good idea but I think converting is not easy beacause I don't find a way in PCL. Do you have any idea of how converting it? Thank you again!

Sorry,I'm affraid I'll let you down, maybe both of us are in the same situation.Once I get the idea I'll reply to you ASAP.
By the way,my data format is las,not pcd

**Comment by kevin-steiner** [comment]
I have done the converting from pcd to h5.

**Comment by SERPENT-H** [comment]
> I have done the converting from pcd to h5.

How did you do it.Could you please offer me your code or your program.Thank u

**Comment by kevin-steiner** [comment]
> > I have done the converting from pcd to h5.
> 
> How did you do it.Could you please offer me your code or your program.Thank u

https://blog.csdn.net/AmbitiousRuralDog/article/details/80455691 I follow this page.

**Comment by SERPENT-H** [comment]
> > > I have done the converting from pcd to h5.
> > 
> > 
> > How did you do it.Could you please offer me your code or your program.Thank u
> 
> https://blog.csdn.net/AmbitiousRuralDog/article/details/80455691 I follow this page.

谢谢
