### ISSUE TITLE
The problem of Point-CNN

### ISSUE THREAD

**Issue by wangyfincug** [yangyanli/PointCNN#218]
when i run 'README.MD' file,this command—— “./train_val_shapenet.sh -g 0 -x shapenet_x8_2048_fps”
an error comes out——
Train/Val with setting shapenet_x8_2048_fps on GPU 0!
and i don‘t know why,could you help me to solve this problem?

**Comment by aldinorizaldy** [comment]
you may check file `pointcnn_seg_shapenet_x8_2048_fps.txt` in `/your_path/models/seg/` to see if there is error message
