### ISSUE TITLE
The Problem about the PointCNN

### ISSUE THREAD

**Issue by kevin-steiner** [yangyanli/PointCNN#219]
![2ce0093a597a45490849e281fb23805](https://user-images.githubusercontent.com/29630934/79424693-21daf680-7ff3-11ea-8375-f2687ada5e46.png)

When I try to run the code with GPU, tensorflow=1.14, it comes the error above. How can I solve it?

**Comment by danbull1** [comment]
Hi Kevin
I stumbled across exactly the same error when attempting to run this code on tf1.14. I fixed this by updating the following line of code: 

iterator = tf.data.Iterator.from_string_handle(handle, dataset_train.output_types,dataset_train.output_shapes)
at line 147 of train_vas_cls.py
i.e. adding an explicit shape to the iterator.

**Comment by kevin-steiner** [comment]
> Hi Kevin
> I stumbled across exactly the same error when attempting to run this code on tf1.14. I fixed this by updating the following line of code:
> 
> iterator = tf.data.Iterator.from_string_handle(handle, dataset_train.output_types,dataset_train.output_shapes)
> at line 147 of train_vas_cls.py
> i.e. adding an explicit shape to the iterator.

Thank you very much, it works well. BTW, do you have any idea of how to get the feature vector of the input data.

**Comment by danbull1** [comment]
Look - Im just in the process of stepping through the code to try and understand what is going on. Points are loaded in this function:
Line122 data_utils: load_cls  loads pts into array e.g. [0:6]  = [0.098043844, -0.16375712, -0.88815236, 0.0, 0.0, 1.0]
