### ISSUE TITLE
ShapeNet Partsegmentation

### ISSUE THREAD

**Issue by edshkim98** [yangyanli/PointCNN#239]
@yangyanli, Hi thank you very much for releasing the code!
I have a question regarding the split of training/val/test dataset of shapenet.
In the paper, you have stated that 'ShapeNet Parts contains 16880 models (14006/2874 training/testing split) from 16 shape categories, each annotated with 2 to 6 parts and there are 50 different parts in total.' which means there is no validation dataset.

Also, in this code https://github.com/yangyanli/PointCNN/blob/master/pointcnn_seg/train_val_shapenet.sh,
it says that test data is used for validation. Does this mean that you have trained the train&validation dataset and then evaluated every epochs and picked the best performance model based on the test dataset?

**Comment by yangyanli** [comment]
@edshkim98, there is no overlap between train_val_files and test_files.
