### ISSUE TITLE
Understanding of downsampling in s3dis_split.py

### ISSUE THREAD

**Issue by yzgfjly** [yangyanli/PointCNN#24]
In data_conversions/split_data/s3dis_split.py   line 73 and 75:
```
            vidx = vidx[:, 0] + vidx[:, 1] * nvox[0] + vidx[:, 2] * nvox[0] * nvox[1]

            uvidx, vpidx = np.unique(vidx, return_index=True)
```
I think the aim of the code is to leave only one point in the same plane while removing other points in the plane. I don't know whether my understand is correct. And I wonder the feature of these planes, such as their shapes and the aim that you chose nvox[0], nvox[0] * nvox[1] as the coefficients.

I would be grateful if you could explain it to me!

**Comment by MingChaoSun** [comment]
For example, input 5 points and res(the size of voxel):
```
pts = [[0.1,0.1,0.1],[0.2,0.2,0.2],[0.3,0.3,0.3],[0.9,0.2,1.5],[2.2,2.2,2.0]]
res = 0.5
```
First, we compute the coordmin and coordmax by the input points(Min [0.1, 0.1, 0.1], Max [2.2, 2.2, 2.0]), then use the res (0.5) to get nvox which means the number of voxel([5, 5, 4]).

For each point we compute the vidx witch means the voxel indices:
```
[[ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 2.  1.  3.]
 [ 5.  5.  4.]]
```
then use the Line 73 to convert 3-dim indices to 1-dim indices: 
```
vidx = vidx[:, 0] + vidx[:, 1] * nvox[0] + vidx[:, 2] * nvox[0] * nvox[1]
#vidx
[0.   31.   31.   82.  130.]
```
use the Line 75 to get the unique vidx(for eatch voxel leave one point):
```
uvidx, vpidx = np.unique(vidx, return_index=True)
#uvidx:
[0.   31.   82.  130.]
#vpidx:
[0 1 3 4]
```
Finally, get the sampled points
```
pts_sampled = pts[vpidx]
```

**Comment by yzgfjly** [comment]
Thanks a lot!
