### ISSUE TITLE
Where is the {scannet_labelmap}?

### ISSUE THREAD

**Issue by sjyhs** [yangyanli/PointCNN#25]
I want to try to make a classification for my point cloud data.

But you write: download [scannet_labelmap] from ScanNet, actually I can't find this file or folder, how can I operate to finish my classification?

Thanks for your attention!

**Comment by MingChaoSun** [comment]
[ScanNet Github README](https://github.com/ScanNet/ScanNet/tree/master/Tasks) explain how to download the label_map:

" Label mappings (scannet-labels.combined.tsv) can be downloaded with the ScanNet task data release. Download with along with the task data (--task_data) or by itself (--label_map). "

the code download-scannet.py provided by ScanNet team have this argument:

```
    parser = argparse.ArgumentParser(description='Downloads ScanNet public data release.')
    parser.add_argument('-o', '--out_dir', required=True, help='directory in which to download')
    parser.add_argument('--task_data', action='store_true', help='whether to download task data')
    parser.add_argument('--label_map', action='store_true', help='whether to download label map file')
    parser.add_argument('--id', help='specific scan id to download')
    parser.add_argument('--type', help='specific file type to download (.aggregation.json, .sens, .txt, _vh_clean.ply, _vh_clean_2.0.010000.segs.json, _vh_clean_2.ply, _vh_clean.segs.json, _vh_clean.aggregation.json, _vh_clean_2.labels.ply, _2d-instance.zip, _2d-instance-filt.zip, _2d-label.zip, _2d-label-filt.zip)')
    args = parser.parse_args()
```

So, you can use --label_map to download the scannet_labelmap~
