### ISSUE TITLE
problem of prepare_multiChannel_seg_data.py about S3DIS

### ISSUE THREAD

**Issue by yzgfjly** [yangyanli/PointCNN#26]
When I run prepare_multiChannel_seg_data.py for S3DIS, I find that list data doesn't match data_num for Area2-Area6.
I don't know whether it will affect the follow-up operation, but I think it would be better if we put line77-80:
`    data = np.zeros((batch_size, max_point_num, args.channel_num))
    data_num = np.zeros((batch_size), dtype=np.int32)
    label = np.zeros((batch_size), dtype=np.int32)
    label_seg = np.zeros((batch_size, max_point_num), dtype=np.int32)`
behind line 81:
`    for data_folder, label_folder in folders:`
Then the list data will match data_num.

**Comment by burui11087** [comment]
Hi,
What's mean of "list data"? I think there is no difference atfer moving line 77-80 behind 81. It's better for us to solve this issue if you can give me more details about that.

Thanks

**Comment by yzgfjly** [comment]
如果line77-80在for循环前，那么在第一次循环时是根据Area1_data在line103,104向data,data_num赋值，在进行第二次循环时并没有把data,data_num重置为0,也就是Area2_data的data,data_num是在Area1_data的data,data_num上进行修改的。举个例子，在第二次循环后，data_num[1] = 4177, 但data[1]中有0：4242共4243组coordinates，也就是data[1][0:4176]是根据Area2_data修改了，但
data[1][4177:4242]还是Area1_data的数据。
我是在单步执行test_general_seg.py的时候发现Area2的data和data_num 数目不匹配的，所以回去查看了prepare_multiChannel_seg_data.py. 我也不知道这个不匹配会不会影响后续操作，但如果把line77-80放在for后面，就不会有不匹配，所以只是一个小小的建议。

非常感谢您的回复！

**Comment by burui11087** [comment]
data的数目声明时候是按照max_point_num的长度来的，如果在Area2_data的data_num[1] = 4177, 那么在train/val/test的时候，网络只会截取到0:4176,后面的值并不会拿出来。 所以不会有什么影响。

不过您的建议会让我们的代码看起来更加清楚。

感谢您的建议，我会Update一下这个更改。
