### ISSUE TITLE
about s3dis_upsampling.py

### ISSUE THREAD

**Issue by yzgfjly** [yangyanli/PointCNN#27]
I am confused about line 95~99 in s3dis_upsampling.py:
`    for k, vid in enumerate(uvidx):`
`        voxel_label_dict[vid] = seg[k]`

`    for vid in vidx:`
`        ori_seg.append(voxel_label_dict[vid])`

Could you please tell me the function of these lines ?

And I trained the model on Area2～6 of S3DIS, then tested on Area1.
If I run s3dis_upsampling.py before running eval_s3dis.py, the output of eval_s3dis.py is:

> [741860, 1081219, 927535, 993140, 209411, 126037, 231132, 105981, 218610, 214055, 21996, 204034, 70819]
[339878, 330121, 640186, 811327, 88785, 99274, 197668, 58156, 122522, 143403, 10943, 116397, 2187169]
[65307, 102514, 164596, 287139, 11102, 36893, 44290, 15898, 16273, 24691, 1482, 35241, 4100]
Overall accuracy: 0.1573169259996786
IoU:
0.06425128710163307
0.07832515552105475
0.11730672605790646
0.18923990066748916
0.03867026130814298
0.19580401023256802
0.11518556084367117
0.10724573155512382
0.050092501669955276
0.07419906421009295
0.04711193057189179
0.12357025141133982
0.001819078853962575
0.09252472769267937

But if I don't run s3dis_upsampling.py, the output of eval_s3dis.py will be  greatly improved:

> [741860, 1081219, 927535, 993140, 209411, 126037, 231132, 105981, 218610, 214055, 21996, 204034, 70819]
[332462, 634309, 554291, 726372, 88278, 83955, 164272, 49907, 104344, 120826, 9476, 95388, 2181949]
[275670, 627944, 547055, 626761, 75240, 76869, 150398, 45148, 86119, 103163, 6392, 80861, 19842]
Overall accuracy: 0.5288675546738922
IoU:
0.3451691099502662
0.5773751728602112
0.5852288956332621
0.5735625041752421
0.33823483135460264
0.5774283932904156
0.6138543545872346
0.40769369694780566
0.36362446428948425
0.44520926298345403
0.25486443381180224
0.369969939742223
0.008886098330173056
0.4200847044581674

Have you ever met this problem?

**Comment by burui11087** [comment]
@yzgfjly Hi
We update split and upsampling files, you can use new code to eval again, I think it will solve your second problem.
Thanks
