### ISSUE TITLE
Problem when running train_val_modelnet.sh

### ISSUE THREAD

**Issue by BandaryWang** [yangyanli/PointCNN#28]
I follow the command:
> cd data_conversions
> python3 ./download_datasets.py -d modelnet
> cd ../pointcnn_cls
> ./train_val_modelnet.sh -g 0 -x modelnet_x2_l4

However, it will generate many model files iteratively. And the error is:

> File "/home/bandary/.conda/envs/my_env/lib/python3.6/shutil.py", line 359, in copytree
>     raise Error(errors)
> shutil.Error: [('/home/bandary/Documents/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_6110_2018-04-13-10-58-25/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_6110_2018-04-13-10-58-25/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_6110_2018-04-13-10-58-25/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_6110_2018-04-13-10-58-25/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_6110_2018-04-13-10-58-25/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_6110_2018-04-13-10-58-25/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_6110_2018-04-13-10-58-25/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_6110_2018-04-13-10-58-25/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_6110_2018-04-13-10-58-25/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_6110_2018-04-13-10-58-25/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_6110_2018-04-13-10-58-25/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_6110_2018-04-13-10-58-25/PointCNN/models/cls/pointcnn_cls_modelnet_x2_l4_

**Comment by yangyanli** [comment]
Hi @BandaryWang,

We were not able to reproduce this problem from our side. Could you provide more detail about this issue?

It seems this issue has something to do with the saving for the code backup...
