### ISSUE TITLE
Scannet train/test size

### ISSUE THREAD

**Issue by ngocminhbui** [yangyanli/PointCNN#29]
I downloaded the scannet dataset and run the code scannet extract object. However, there are only 7815 instances in the trainset and 2170 in the testset compared to 9035 and 2060 respectively stated in the PointCNN paper. 

Also when i run the conversion code, I faced "index out of range error" when extract ShapeNetCore 55 labbel: ShapeNetCore55 = line_s[11] . I removed the strip function line_s = line.strip().split('\t') and it works but result in inconsistent train/test size. 
Can you have a look of this issue. Thank you.

**Comment by MingChaoSun** [comment]
This problem is due to the “None” value in the scannet-labels.combined.tsv. Now we upload our scannet-labels.combined.tsv which delete the “None” value and fix some error values in the file. You can have a try~

**Comment by ngocminhbui** [comment]
I believe the out of range problem is due to the strip() function, that strips out multiple '\t' at the end of a line. I downloaded your updated 'scannet-labels.combined.tsv' and ran extraction code again but the train/test size is still inconsistent.  Can you upload the files "classes_ObjClassification-ShapeNetCore55.txt" you used to benchmark ? Because I observe there're different in label names in that file (classes_ObjClassification-ShapeNetCore55.txt) versus the label of each object instance, e.g. 'trash' vs 'trash_bin', 'book' vs 'bookshelf', etc...

**Comment by MingChaoSun** [comment]
Here is our [classes_ObjClassification-ShapeNetCore55.txt](https://github.com/yangyanli/PointCNN/blob/master/data_conversions/classes_ObjClassification-ShapeNetCore55.txt),.
I'm sorry I've forgotten some details that we have fixed the benchmark files for the different label names problems. We have the same problem as you mentioned, like the 'trash' and 'trash_bin'. Scannet Paper mentioned:"For this benchmark, we use 17 categories,
with 9, 677 train instances and 2, 606 test instances.", so we fixed the benchmark files to extract more instances.
If there are any other questions, please feel free to contact us~

**Comment by ngocminhbui** [comment]
Can you show me how to fix these benchmark files to obtain the correct size of train/test split? thank you
