### ISSUE TITLE
about the fine tune?

### ISSUE THREAD

**Issue by lfxx** [yangyanli/PointCNN#30]
1.I have tried your framework,it did works well.But now i want use it to detect fruits,such as orange.How can i fine tune the net to achieve my target?Should i make 3D datasets which just includes orange?Just like make VOC2007 datasets using 2D conv?I plan to use scannet datasets form to make my own datasets,is this proper?
2.你好，我试用了你们的网络，用的是scannet数据集跑的，效果确实不错。我现在想拿它来识别柑橘，实现这种目标需要调优网络吧，那么数据集怎么做呢，自己仿造scannet数据集就可以吗，之前自制VOC2007数据集已经是轻车熟路了，但是3D数据集还不是太了解，感觉这个网络的hyper-para比2D的网络要多啊，会不会很难调？期待您的回复！

**Comment by yangyanli** [comment]
Hi @lfxx,

I think there can be two potential directions:
1. Synthesize data: if your testing data is not too far from what you can synthesize, then I think the model trained on synthetic dataset should work reasonably well on real data.
2. Scan and label real data:  if 1 doesn't work, probably you have to go through this approach. Similar to  how ScanNet was created.

**Comment by lfxx** [comment]
采用第二种方法的话，还是需要在scannet数据集上做预训练吧，然后再在自己的训练集上调优？

**Comment by yangyanli** [comment]
Maybe, I cannot tell...

It depends on the object types you want to work with, as well as how much data you can scan/label.

**Comment by lfxx** [comment]
1.The datasets made on my own is small,so is it a good idea to get the net pretrained on scannet datasets?
2.我自制的数据集肯定是比较小的那种，所以感觉还是需要预训练一下，这样效果可能会比较好?

**Comment by yangyanli** [comment]
Try it ;-)
