### ISSUE TITLE
Reasons on using separable convolution

### ISSUE THREAD

**Issue by amiltonwong** [yangyanli/PointCNN#32]
Hi, @yangyanli ,

I found that there are some [places](https://github.com/yangyanli/PointCNN/blob/master/pointcnn.py#L38-L47) which uses separable convolution. What's the purpose on using it rather than conventional convolution operation? I didn't find any explanation on it in PointCNN paper.  Is the performance reason or memory cost reason on using separable convolution?

THX!

**Comment by yangyanli** [comment]
The use of separable convolution is mostly for reducing parameter number/overfitting.

The benchmark datasets are rather small compared with those image world datasets. We observed strong overfitting in the early development of PointCNN, and since then we switched to separable convolution.

**Comment by amiltonwong** [comment]
Thanks a lot! @yangyanli
