### ISSUE TITLE
The problem about environment

### ISSUE THREAD

**Issue by LinZhuoChen** [yangyanli/PointCNN#34]
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "../train_val_seg.py", line 271, in <module>
    main()
  File "../train_val_seg.py", line 126, in main
    t_1_acc_op, t_1_acc_update_op = tf.metrics.precision_at_k(labels_sampled, logits, 1)
AttributeError: module 'tensorflow.python.ops.metrics' has no attribute 'precision_at_k'

And I find that the API 'precision_at_k' only exists in tensorflow 1.5 and above, how could you test the code in the environment tensorflow 1.4?

Thank you very much!

**Comment by burui11087** [comment]
Hi @LinZhuoChen 
It is recommended to use tensorflow 1.6+, because fps sampling unable to compile directly in the environment 1.5.
If you can only use 1.5 (can't install cuda9 on ubuntu 14.04), I suggest following: [https://github.com/tensorflow/tensorflow/issues/15188]

**Comment by burui11087** [comment]
@LinZhuoChen  
I will close this issue and if you have similar problem, you can reopen it

**Comment by Lareina-LUO** [comment]
Hi, you said we need TF1.4 to compile the tf_sampling in issues 5. But we must install TF1.5+ to use the function tf.metrics.precision_at_k. Do you mean that  you implemented the code based on TF1.4 before, but now update the code based on TF1.6?
