### ISSUE TITLE
the code about shapenet segmentation

### ISSUE THREAD

**Issue by meteorshowers** [yangyanli/PointCNN#35]
When I run the segmentation task on shapenet dataset, there is an error about max() is empty.
The code is in the prepre_partseg_data.py  55th line(category_label_seg_max_list is empty).
I am confused about it.
Thank you!

**Comment by meteorshowers** [comment]
I find the solution, maybe there is a path error in your code.
The user can change the code from >>root +'train_data'     to  >> root+'/train_data' in your folder setting code. The others are the same like this. 
Thank you!

**Comment by burui11087** [comment]
Hi @meteorshowers 
Thanks for your report.
There is "/" in the end of root variable in our code, but it's not convenient for others, like you, need to modify the root, I will improve the quality of code immediately.
Thank you
