### ISSUE TITLE
test on shapenet

### ISSUE THREAD

**Issue by meteorshowers** [yangyanli/PointCNN#36]
I try to test shape net dataset on the trained model,  however, there is an error that when the code run into the pointcnn.py, the terminal tells me that the net has no attributes about probs(simply there is >>no net.probs in the test_seg.py ).
Could you tell me how to change the code to make it run?
Thanks a lot!

**Comment by meteorshowers** [comment]
there are lots of code version problem in your shapenet test code.
I tried to use the elder version code, however, there is also version confliction.
I will appreciate it if you can fix this problem so that I can evalue your pointcnn model on the segmentation task.
I think it is an important thing, thanks a lot!

**Comment by yangyanli** [comment]
Sorry for the issue! There were some net interface changes. Could you try the latest version?
