### ISSUE TITLE
The problem about shapeNet

### ISSUE THREAD

**Issue by LinZhuoChen** [yangyanli/PointCNN#37]
When I run this command"./test_shapenet.sh -g 0 -x shapenet_x8_2048_fps -l ../../models/seg/pointcnn_seg_shapenet_x8_2048_fps_xxxx/ckpts/iter-xxxxx -r 10"
The error occured in test_seg.py line 94:probs_op = net.probs.It tells me that no probs attribute in net.
The net is defined in pointcnn.py and I didn't find the self.probs in object point cnn.
And I found that in the previous version of point cnn.
If this is a bug, can you fix it?
Thank you!

**Comment by yangyanli** [comment]
Duplicate of #36
