### ISSUE TITLE
The output of file_seg is -1

### ISSUE THREAD

**Issue by yzgfjly** [yangyanli/PointCNN#39]
When I run test_s3dis.sh, I find that in the beginning, the contents of output ".seg" files are normal, which are indexes of max point_seg_probs. But the output ".seg" files corresponding to the files which are later processed are abnormal. The contents of these ".seg" files are all "-1".

And I run test_general_seg.py in "debug" mode of PyCharm for several "for" loops, the output ".seg" files are all normal, but it become "-1" again once using "run" mode of PyCharm for later processed files.

In test_general_seg.py, line 136-153:
```
            for idx in range(sample_num*batch_size):
                point_idx = indices_shuffle[idx]
                point_seg_probs = seg_probs_2d[idx, :]
                prob = np.amax(point_seg_probs)
                seg_idx = np.argmax(point_seg_probs)
                if prob > predictions[point_idx][1]:

                    predictions[point_idx] = [seg_idx, prob, point_seg_probs]

            labels = []
            with open(output_filelist[batch_idx], 'w') as file_seg:
                for seg_idx, prob, probs in predictions:

                    file_seg.write(str(int(seg_idx)))

                    file_seg.write("\n")

                    labels.append(seg_idx)
```
The seg_idx write to file_seg is np.argmax(point_seg_probs), which can't be "-1". 

I am really confused, could you please help me ?

**Comment by yangyanli** [comment]
Could you check the content of point_seg_probs when np.argmax(point_seg_probs) is -1?

**Comment by yzgfjly** [comment]
I think this problem may be caused by the data set which is too large. I divide the data set to four small data set and run test_general_seg.py respectively, then it worked well.

**Comment by yangyanli** [comment]
Many thanks for the update!

It would be great if you can track down the problem, and send us a pull request with your fix.
