### ISSUE TITLE
What's the intention for map_fn

### ISSUE THREAD

**Issue by amiltonwong** [yangyanli/PointCNN#4]
Hi, authors,

What's the purpose for [map_fn](https://github.com/yangyanli/PointCNN/blob/master/pointcnn_cls/modelnet_x2_l4.py#L11), which we could find many places referring to? e.g. line [65](https://github.com/yangyanli/PointCNN/blob/master/train_val_cls.py#L65) , line [96](https://github.com/yangyanli/PointCNN/blob/master/train_val_cls.py#L96), line [114](https://github.com/yangyanli/PointCNN/blob/master/train_val_cls.py#L114) in `train_val_cls.py`

**Comment by yangyanli** [comment]
This is mainly for “mapping” Quick Draw stokes into point cloud on the fly.

For data which is already point cloud, it is not used.

The new data loading API of Tensorflow is quite flexible ;-)
