### ISSUE TITLE
therre is a problem when i run train_val_cls.py

### ISSUE THREAD

**Issue by 760146355** [yangyanli/PointCNN#40]
parser = argparse.ArgumentParser()
    parser.add_argument('--path', '-t', help='Path to data', default='/home/data/modelnet40_ply_hdf5_2048/train_files.txt') 
    parser.add_argument('--path_val', '-v', help='Path to validation data',default='/home/data/modelnet40_ply_hdf5_2048/test_files.txt')
    parser.add_argument('--load_ckpt', '-l', help='Path to a check point file for load')
    parser.add_argument('--save_folder', '-s', help='Path to folder for saving check points and summary', default='/home/data/save/')
    parser.add_argument('--model', '-m', help='Model to use', default='pointcnn_cls')
    parser.add_argument('--setting', '-x', help='Setting to use', default='modelnet_x3_l4_p032')
    args = parser.parse_args()

i changed your code as above,and i got an error blow

InvalidArgumentError (see above for traceback): clip_value_min and clip_value_max must be either of the same shape as input, or a scalar. input shape: [128,32,3]clip_value_min shape: [1]clip_value_max shape: [1]
	 [[Node: jitter_clipped = ClipByValue[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](mul, mul_1, mul_2)]]

 
thanks for your help!

**Comment by yangyanli** [comment]
Hi,

We cannot reproduce your problem since we don't have your code. Anyway, it seems to be a parameter mis-matching problem, could you try to resolve it by following the error message?

**Comment by l53ma** [comment]
@760146355 

Hi there. I met the same error as you mentioned above. Have you solved this issue? If so, would you mind sharing your solution? 

Thank you.
