### ISSUE TITLE
Concerns about classification-modelnet40

### ISSUE THREAD

**Issue by l53ma** [yangyanli/PointCNN#41]
Thanks for sharing your great work!

I am a beginner of deep learning models used on point clouds. I am very interested about your achievement. However, I have one question when conducting Classification operation on ModelNet40. You said performed "/train_val_modelnet.sh -g 0 -x modelnet_x3_l4", and it output "Train/Val with setting modelnet_x3_l4 on GPU 0!", then nothing happened. I would like to know how to achieve classification function, can you give the details steps after getting the above message? My operating environment is Ubuntu16.04 + python3.5
Thank you for your kind assistance.

**Comment by yangyanli** [comment]
From our homepage ReadMe:

If you want to moniter your train step, we recommand you use following command
```
cd <your path>/PointCNN
tensorboard --logdir=../models/<seg/cls> <--port=6006>
```

Also, the txt logs are written to PointCNN/models/<seg/cls>/xxxxx/log.txt.

**Comment by l53ma** [comment]
Thank you for your answers.

I would like to make my concerns more clear. What should be the next procedure for classification after  "/train_val_modelnet.sh -g 0 -x modelnet_x3_l4". Which files should be afterward compiled? 

Your ReadMe file is not very clear to follow.

Thank you yangyan, for your kind help.

**Comment by yangyanli** [comment]
Hi @l53ma ,

We recommend you take a look at some machine learning & tensorflow 101 tutorials, which will explain some basics of the procedure, and then everything will be much more clear.
