### ISSUE TITLE
Problem with ScanNet Classification

### ISSUE THREAD

**Issue by BrennoCaldato** [yangyanli/PointCNN#43]
Hi, 

I'm having some issues with the preprocessing of ScanNet dataset for classification.

When I try to run the command:
python scannet_extract_obj.py -f ../../data/scannet/scannet_dataset_download/data/ -b ../../data/scannet/scannet_dataset_download/benchmark/ -o ../../data/scannet/cls/

The script crashes with this error:

Traceback (most recent call last):
  File "scannet_extract_obj.py", line 375, in <module>
    main()
  File "scannet_extract_obj.py", line 336, in main
    sceneid = scene.strip().split("scene")[1]
IndexError: list index out of range

The scene variable when the crash occurs is with the string:
scene:  ../../data/scannet/scannet_dataset_download/data//h5_scannet

Has anyone had the same problem?
Thanks

**Comment by MingChaoSun** [comment]
Hi,

The Scannet dataset we download for classification seems to be different from yours.
The directory format is like this:

Dataset root: ./scannet/

Subdirectory: total 6195

./scannet/scene0000_00/
./scannet/scene0000_01/
./scannet/scene0000_02/
./scannet/scene0001_00/
./scannet/scene0001_01/
./scannet/scene0002_00/
./scannet/scene0002_01/
./scannet/scene0003_00/
./scannet/scene0003_01/
./scannet/scene0003_02/
./scannet/scene0004_00/
./scannet/scene0005_00/
./scannet/scene0005_01/

...

./scannet/scene0703_00/
./scannet/scene0703_01/
./scannet/scene0704_00/
./scannet/scene0704_01/
./scannet/scene0705_00/
./scannet/scene0705_01/
./scannet/scene0705_02/
./scannet/scene0706_00/

each scene folder contains .ply and .json files.

In addition, there are some problems in the original benchmark files, you can refer to this issue:
https://github.com/yangyanli/PointCNN/issues/29

**Comment by BrennoCaldato** [comment]
Hi, thanks for the reply,

I've followed the Readme instructions that says 
"Please refer to http://www.scan-net.org/ for downloading ScanNet task data and scannet_labelmap"
When I download the task data it just gave me a .h5 file.

To fix this problem I had to download all the .json and .ply files
