### ISSUE TITLE
module 'shapenet_x8_2048_fps' has no attribute 'step_val'

### ISSUE THREAD

**Issue by cmc233** [yangyanli/PointCNN#44]
Hi ,thanks for your share!
When I try to train the shapenet_x8_2048_fps, I accept an error :
File "../train_val_seg.py", line 51, in main
    step_val = setting.step_val
AttributeError: module 'shapenet_x8_2048_fps' has no attribute 'step_val'
I checked shapenet_x8_2048_fps.py and found it did not contain "step_val ". What value should be set for step_val ?
Awaiting for your reply .Thank you very much!

**Comment by yangyanli** [comment]
Hi @cmc233 ,

This is a parameter saying that an evaluation pass will be run after step_val training batches.  Hope this information can help you set it accordingly.

We are working on a pass to clear such problems, and will release an update soon.
