### ISSUE TITLE
High memeory occupation in training for segmentation

### ISSUE THREAD

**Issue by cmc233** [yangyanli/PointCNN#45]
Hi ,thanks for your share!
Because my GPU doesn't satisfy the requirement of TensorFlow with GPU, I just use the CPU to do the training. It does work, but I find  it occupy 100%CPU and 98%RAM (CPU: i5, RAM: 8G) when I train the shapenet_x8_2048_fps for segmentation, even though I just load only one .h5 file ( which is only 162Mb).
There is anything wrong with my training? Or everything is OK?
Waiting for your reply. Thank you very much!

**Comment by yangyanli** [comment]
Hi @cmc233 ,

The segmentation network does requires large amount of memory, we trained them in GPU with 16GB memory.

You can try to reduce the memory consumption by reducing batch size or channel number (e.g., x = 4). The models trained with smaller batch size or channel number performs slightly worse than the default setting we provided.

btw, we didn't try, but training on CPU may take weeks...
