### ISSUE TITLE
Problem in data_utils.py

### ISSUE THREAD

**Issue by tiger6998** [yangyanli/PointCNN#47]
line 113-114
In load_cls()
```python
if 'normal' in data:
    points.append(np.concatenate([data['data'][...], data['data'][...]], axis=-1).astype(np.float32))
```
It seems if there are normal vectors in the file, coordinates will be used again as features for the the first X-Conv layer.

But in the paper, it says: 

"For input point cloud without any additional features, i.e., F is empty, the first X-Conv layer uses only Fδ ."

So does this step improve the performance?
If I concatenate  coordinates with normal vectors, will it help?

**Comment by yangyanli** [comment]
They are loaded, but not used, see: https://github.com/yangyanli/PointCNN/blob/master/train_val_cls.py#L139

They can be used if we set:
use_extra_features = True
with_normal_feature = True
like that in https://github.com/yangyanli/PointCNN/blob/master/pointcnn_cls/modelnet_x3_l4_w_fts.py

However, we found it barely improve the performance. We suspect the normals can be helpful if the dataset is much larger and more robust to overfitting.

**Comment by tiger6998** [comment]
@yangyanli Thanks for your response, I see.
I was just wondering why you concatenate 'data' twice like:
```python 
np.concatenate([data['data'][...], data['data'][...]], axis=-1)
```
instead of concatenating data and normal like
```python 
np.concatenate([data['data'][...], data['normal'][...]], axis=-1)
```

**Comment by yangyanli** [comment]
Nice catch, @tiger6998! It is a bug!

Let me fix it and see if it will perform better.

This bug also explains why we didn't observe a performance gain when we enable normals :D

**Comment by yangyanli** [comment]
Fixed, and it performs consistently better, though with a small margin, when the normals are used.
