### ISSUE TITLE
Core Dump when import tf_sampling

### ISSUE THREAD

**Issue by kimren227** [yangyanli/PointCNN#5]
Hi Yangyan,
I have compiled the tf_sampling module, however, when I try to import it, "segmentation fault (core dumped)" happens. Is there anything I need to pay attention of while compiling the module? (TF version, cuda,gcc version?)
Thanks,
Daxuan

**Comment by burui11087** [comment]
we compile it in TF1.4. could you paste more information when you compile tf_sampling ?
Thanks

**Comment by kimren227** [comment]
Hi, thanks for the reply.
I find the problem. I was compile and run it in a virtualenv, but in the compile.sh file it use the native Python3. So the compilation with not report any error however when trying to run it in the virtualenv, it cause the segmentation fault.
After switching to native envoriment and using TF1.4, problem solved.
Thanks
