### ISSUE TITLE
Memory Occupation for Shapenet

### ISSUE THREAD

**Issue by DasVergissmeinnicht** [yangyanli/PointCNN#50]
I tried to train Shapenet on P40 with 20 GB memory but it still needs more memory. 
The config is the default one which you provided with batch_size = 24 but the log file told me that the memory is not enough for creating new blocks.
By the way, could you please tell me about your training config?
Thank you!

**Comment by burui11087** [comment]
Hi @DasVergissmeinnicht 

We set batch_size=24 trained on p100 which has 16GB GPU memory and it's enough.  could you set batch_size smaller, such as 12, and see whether it works.

You can also see OOM at which layer , it can help you to choose  a suitable batch size

**Comment by DasVergissmeinnicht** [comment]
@burui11087 Thank you for your reply!
We can run batch_size = 12 on our machine but we still hope to run as batch_size = 24 to make the result better.

**Comment by burui11087** [comment]
@DasVergissmeinnicht happy to see it works.

Did you modify other hyper-parameter in config file? such as conv layer, channel number.

**Comment by DasVergissmeinnicht** [comment]
@burui11087 No, I just directly used the default provided config.

**Comment by burui11087** [comment]
@DasVergissmeinnicht Hi

I updated new config file, you can use it to train your model. 

I think you can run batch_size = 20 on your machine. 

Thanks

**Comment by DasVergissmeinnicht** [comment]
@burui11087 

Thank you for your updating!
I will try it on my machine.
Thanks
