### ISSUE TITLE
How is the performance for the arbitrary rotation?

### ISSUE THREAD

**Issue by godspeed1989** [yangyanli/PointCNN#54]
I notice for the classification task, this project rotates data just along one axis.
Although data augment supports arbitrary rotation, you don't use it.

Will the arbitrary rotation further increase performance?

**Comment by burui11087** [comment]
Hi @godspeed1989 , thanks for your attention.

On most of classification tasks, such as ModelNet, training and testing models are already aligned. If we don't rotate horizontal axis, we can get better performance.

For last question, PointNet/PointNet++, as well as the 3DCNN work, they all assume that the horizontal rotations of the testing models are unknown, and to address this problem, the training models are randomly rotated horizontally to augment the data.

**Comment by godspeed1989** [comment]
Thanks, burui.

Do you know is there any network that is invariant to the arbitrary rotation?

**Comment by godspeed1989** [comment]
Thanks a lot :+1:

**Comment by burui11087** [comment]
@godspeed1989 

Hi, I will close this issue. Please feel free to open new issue if you have other problem.
