### ISSUE TITLE
Advice on how to run on a dataset with large pointcloud

### ISSUE THREAD

**Issue by aniqueakhtar** [yangyanli/PointCNN#56]
Hello,
I have an outdoor dataset with about 32k points per pointcloud.
So sample_num = 32768 and I cannot decrease it anymore because I would be losing valuable information. The data is already downsampled.

The current architecture is this:

```
batchsize = 2

x = 1

xconv_param_name = ('K', 'D', 'P', 'C', 'links')
xconv_params = [dict(zip(xconv_param_name, xconv_param)) for xconv_param in
                [(8, 1, -1, 32 * x, []),
                 (12, 2, 768, 64 * x, []),
                 (16, 2, 384, 96 * x, []),
                 (16, 4, 128, 128 * x, [])]]

with_global = True

xdconv_param_name = ('K', 'D', 'pts_layer_idx', 'qrs_layer_idx')
xdconv_params = [dict(zip(xdconv_param_name, xdconv_param)) for xdconv_param in
                 [(16, 4, 3, 3),
                  (16, 2, 2, 2),
                  (12, 2, 2, 1),
                  (8, 2, 1, 0)]]

fc_param_name = ('C', 'dropout_rate')
fc_params = [dict(zip(fc_param_name, fc_param)) for fc_param in
             [(32 * x, 0.0),
              (32 * x, 0.5)]]
```

But it keeps running out of memory.

Could you please guide me as to what could be the most efficient method of decreasing the architecture size without degrading the results too much.

Thank you.

**Comment by burui11087** [comment]
@aniqueakhtar Hi

There are many methods to do that.

The simplest method is decrease 'C'(channel number),such as 128 ->96, you can also decrease 'K' and 'D', I don't think outdoor dataset need so big reception field, and won't lead to Acc losing. 

Here is a example:
                [(8, 1, -1, 32 * x, []),
                 (12, 1, 512, 64 * x, []),
                 (16, 1, 256, 96 * x, []),
                 (16, 3, 96, 128 * x, [])]]

If above doesn't work, I recommend split the input to several block like S3DIS or set batch size to 1

**Comment by aniqueakhtar** [comment]
I find it very strange that the first architecture runs and the 2nd one always runs out of memory. Any specific reason for that?
I also believe that variable 'D' wouldn't change the memory allocation much.

Architecture 1 =
```
batch_size = 2
x = 4
xconv_param_name = ('K', 'D', 'P', 'C', 'links')
xconv_params = [dict(zip(xconv_param_name, xconv_param)) for xconv_param in
                [(8, 1, -1, 32 * x, []),
                 (12, 1, 6144, 32 * x, []),
                 (16, 1, 1536, 32 * x, []),
                 (16, 3, 384, 64 * x, [])]]
xdconv_param_name = ('K', 'D', 'pts_layer_idx', 'qrs_layer_idx')
xdconv_params = [dict(zip(xdconv_param_name, xdconv_param)) for xdconv_param in
                 [(16, 4, 3, 3),
                  (16, 2, 2, 2),
                  (12, 2, 2, 1),
                  (8, 2, 1, 0)]]
```

Architecture 2=
```
batch_size = 3
x = 1
xconv_param_name = ('K', 'D', 'P', 'C', 'links')
xconv_params = [dict(zip(xconv_param_name, xconv_param)) for xconv_param in
                [(8, 1, -1, 16 * x, []),
                 (8, 1, 6144, 16 * x, []),
                 (8, 2, 1536, 32 * x, [])]]
xdconv_param_name = ('K', 'D', 'pts_layer_idx', 'qrs_layer_idx')
xdconv_params = [dict(zip(xdconv_param_name, xdconv_param)) for xdconv_param in
                  [(8, 2, 2, 2),
                  (8, 1, 2, 1),
                  (8, 1, 1, 0)]]
```

I have tried to condense the 2nd architecture to be able to process more batches. 2 batches typically do not have enough information to give better results.

**Comment by Emma0928** [comment]
@aniqueakhtar Hi:
I want to use my own data sets to train pointcnn ,but I can't transform obj files into proper hdf5 files.Could you please give me some suggestions?
Thank you very much!
