### ISSUE TITLE
About how to get results of  classification based on Modelnet using PointCNN correctly

### ISSUE THREAD

**Issue by Kyle-YK-Yu** [yangyanli/PointCNN#58]
Hello,I  am a student from Shanghai Jiao Tong University. Our team is working on  refining your PointCNN's performance of classification task. However,  we have difficulties getting the results about classification task based  on data from Modelnet when running your codes in the command window  under the Ubuntu 16.04 system. It seems that the GPU is not working  although we implement your instructions in Github Readme.md.

 File 1 shows our code in the command window. The modelnet files have  been downloaded successfully as shown in file 2. And we have put the  folder:PointCNN-master on the Desktop. Although the last line suggests that training task   has been implemented by GPU 0, we can see that this is not the case when watching its low utilization ratio as shown in file 3. 

We would like to ask what is the reason of this phenomenon, and we  really appreciate your attention and feedback. Thank you for your time!
![file1](https://user-images.githubusercontent.com/25402933/43504645-cb5da9b2-9596-11e8-978e-2b631ccd4775.png)
![file2](https://user-images.githubusercontent.com/25402933/43504646-cb9aa4e8-9596-11e8-840b-d7ecb510c21d.png)
![file3](https://user-images.githubusercontent.com/25402933/43504648-cbd6c36a-9596-11e8-91e3-7ea283a01980.png)

**Comment by burui11087** [comment]
Hi @Kyle-YK-Yu 
I think you should find the folder named "models" firstly and there is a log file can tell you what happened. 

From my experience, there have two reasons. 1, program can't find data folder. 2, [`shutil.copytree()`] in train_val_cls.py copy files endless because train_val_modelnet.sh _model save path_ is modified.

**Comment by Kyle-YK-Yu** [comment]
Hi, @burui11087 
Thanks for your reply! We have checked the folder:models/cls. And there is a file called pointcnn_cls_modelnet_x3_l4.txt(which should reflect the settings of the training task). It reports an error in the process of running the codes as shown in the picture below. Could you tell me why this error exists. Our tensorflow's version is 1.8.0 and Python version is 3.5. Thanks a lot!
![2018-08-01 15-09-26](https://user-images.githubusercontent.com/25402933/43506750-a43b611a-959d-11e8-8a1e-5eccc7580ae7.png)

**Comment by burui11087** [comment]
If you have other problems, you can reopen this issue again :)
