### ISSUE TITLE
OnLine classification

### ISSUE THREAD

**Issue by dvm1607** [yangyanli/PointCNN#59]
Hello, can we use the PoinCNN for online classification? If so do you have any examples? classification from a data source that does not have multiple angles?

**Comment by yangyanli** [comment]
Hi @dvm1607 ,

Sorry but I feel I need more details to understand your problem. Could you elaborate more on your problem and usage?

**Comment by yangyanli** [comment]
@dvm1607 ,

For online classification, I think you have to train the model, then freeze the model, and finally load and inference with tensorflow C++ API. The details are beyond the scope of this project, please Google on such topics.

For the fixed angles, sure, if you have the same training data. What we provided is a general method, and I think it can be adapted to your problem. However, you do have to understand the algorithm well to make a good adaptation.
