### ISSUE TITLE
Settings without .sh file

### ISSUE THREAD

**Issue by dvm1607** [yangyanli/PointCNN#60]
Hello, I'm trying to run the example on windows, so I don't have an option to use bashfiles (at least the ones I tried failed).

It is my understanding that the last line of the file train_val_mnist.sh, is the one that actually puts everything together. So I have tried to set the values manually instead of using the bashfile code, however, the last parameter "setting" seems to come from a txt file. 

"CUDA_VISIBLE_DEVICES=$gpu python3 ../train_val_cls.py -t $train_files -v $val_files -s $models_folder -m pointcnn_cls -x $setting > $models_folder/pointcnn_cls_$setting.txt 2>&1 &"

How can I obtain the values from this txt file manually?

**Comment by yangyanli** [comment]
Hi @dvm1607,

The last parameter is NOT a necessary input. It is for outputting stdout and stderr into a .txt file.
