### ISSUE TITLE
about running of semantic 3d dataset

### ISSUE THREAD

**Issue by yangLiu1022** [yangyanli/PointCNN#61]
hi,
when i run the code with semantic3d dataset,there are many question.
eg.1.when i run ./train_val_semantic3d.sh -g 0 -x semantic3d_x8_2048_k16
       show the probrom:/usr/bin/env: ‘bash\r’: No such file or directory
      2.and i find the file you provide have some missing,such as "test_semantic3d.sh" and so on
and may you provide the semantic3d dataset of ''.h5'' in the files?

**Comment by yangLiu1022** [comment]
hi,
I try again,and i find that the train and test file(.h) have been merged and shuffled,but the path in train_val_semantic3d.sh is separate.So there are some probloms when i try again.

**Comment by burui11087** [comment]
Thank you for waiting

You can duplicate prepare_semantic3d_filelists.txt line 32 - line 48 and use "val" instead of "train_val" to generale val_filelists.txt

Thanks
