### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by mjchen611** [yangyanli/PointCNN#63]
Hi,

I'm a little curious about the training time on ModelNet40.

How many epochs it use to train the model on ModelNet40?

How long  it takes to train the model on ModelNet40?

Thank you.

**Comment by burui11087** [comment]
@ctarn Hi

I just get training time information when batch_size=16, input number=1024, it's not suitbale for the configurations  that supplied in our repo.I recommend you using tensorflow timeline to get this information.:)

If you using P100, I think half a day is proper. 

Thanks!
