### ISSUE TITLE
The purpose of using xzyrgb instead of xyzrgb in data preprocessing

### ISSUE THREAD

**Issue by yzgfjly** [yangyanli/PointCNN#65]
Hi,
I notice that in prepare_s3dis_data.py and prepare_semantic3d_data.py, the coordinates of data are split an then concatenate as the order of x, z, y

`                    x, y, z = np.split(block_points, (1, 2), axis=-1)`
`                   block_xzyrgb = np.concatenate([x, z, y, block_rgb], axis=-1)`

Could you please tell me the purpose of using xzyrgb instead of xyzrgb in data preprocessing?

**Comment by burui11087** [comment]
Hi
Because x, y, z will make scenes upside down.

BTW,You can use "-s" parameter when you preparing S3DIS dataset to visualize.

**Comment by yzgfjly** [comment]
Thanks for your response
