### ISSUE TITLE
Something wrong with download

### ISSUE THREAD

**Issue by yundumbledore** [yangyanli/PointCNN#67]
Hi, thanks for your work. I'm trying to run this package in my laptop.

While running **python3 ./download_datasets.py -d modelnet**, so many errors occurs.

Here is part of the error msg:
_Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1806, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1546, in _raise_ssl_error
    _raise_current_error()
  File "/anaconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]_

I'm just wondering if this is the configuration problem or something wrong with my anaconda. Do I need to do minor changes on system files before running your package?

Sincerely,
Rowen

**Comment by yangyanli** [comment]
Hi Rowen,

These downloading related scripts are prepared to automate the reproduction of our paper. However, they are not being well maintained, it may fail it the data server has changed, or you have bad connect to the server, etc...

In these cases, we suggest you download the data yourself, and take a look at the scripts for figuring out where to put them for the follow up steps.
