### ISSUE TITLE
What's the meaning of "with_fps"

### ISSUE THREAD

**Issue by amiltonwong** [yangyanli/PointCNN#7]
Hi, authors,

What's the meaning of `with_fps`, which found in `modelnet_x2_l4.py`? It'll be much useful if more comments could be appended for each main parameters in `modelnet_x2_l4.py`.

P.S. I finally found the meaning of `fps`. That's "Furthest point sampling" from [here](https://github.com/yangyanli/PointCNN/blob/master/sampling/tf_sampling.py#L1)  , right? 

THANKS

**Comment by yangyanli** [comment]
Yes ;-)
