### ISSUE TITLE
something about "requests"

### ISSUE THREAD

**Issue by kangzhiheng** [yangyanli/PointCNN#72]
hi, i met a problem, when I run the code as followed(ubuntu 16.04LTS, tensorflow 1.6)
"python ./download_datasets.py -d modelnet"
then something was showed,
"aise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='shapenet.cs.stanford.edu', port=443): Max retries exceeded with url: /media/modelnet40_ply_hdf5_2048.zip (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
(tensorflow) "
what's wrong?

**Comment by yangyanli** [comment]
Please google such error messages, and maybe try to download the dataset without using our scripts.
