### ISSUE TITLE
the filefold named 'split_data'?

### ISSUE THREAD

**Issue by YukioSama** [yangyanli/PointCNN#76]
sorry ,i cant find the filefold named 'split_data',is there the filefold？
`For big scene point cloud datasets like **Scannet** and **S3DIS**, we split them into small blocks for training:

```
python3 split_data/scannet_split.py
````

**Comment by burui11087** [comment]
Hi @YukioSama 

I think you are using old version of README.md, We have updated it several months ago. As far as I'm concerned, it's better to pull all files in this repo again

Thanks

**Comment by YukioSama** [comment]
thank you for your reply! I will update it to try
