### ISSUE TITLE
Can't run eval_scannet.py

### ISSUE THREAD

**Issue by forvd** [yangyanli/PointCNN#77]
block_data_root = "../../data/scannet/scannet_split_dataset/val_data/01/"
block_label_root = "../../data/scannet/scannet_split_dataset/val_label/01/"
block_trans_root = "../../data/scannet/scannet_split_dataset/val_trans/01/"
block_pred_root = "../../data/scannet/scannet_split_dataset/val_data/pred_4/01/"

save_voxel_re = True

seg_pred_out_root = "../../data/scannet/scannet_split_dataset/val_data/pred_4/out/seg_pred_voxel/"
seg_label_out_root = "../../data/scannet/scannet_split_dataset/val_data/pred_4/out/seg_label_voxel/"
pts_out_root = "../../data/scannet/scannet_split_dataset/val_data/pred_4/out/pts_voxel/"

The origin code is here. I can't find scannet_split_dataset in my pc. I used scannet pickle files provided by pointnet++. Should I download the origin scannet? Or maybe it's an update bug that you missed?

**Comment by MingChaoSun** [comment]
Hi @forvd 

I have fixed this update bug, we rewrite the data preprocessing code (cut the point cloud into blocks), but forgot to update the evaluation code. BTW, I fixed the update_ops problem in test_general_seg.py that may cause predict values all 0， and for merge the blocks to original room scene， I add room_id record in prepare_scannet_seg_data.py. 

So, please update your code and prepare new dataset with room_id (```python3 prepare_scannet_seg_data.py```), then use your model test and eval again.

```
./test_scannet.sh -g 0 -x scannet_x8_2048_k8_fps -l ../../models/seg/pointcnn_seg_scannet_x8_2048_k8_fps_xxxx/ckpts/iter-xxxxx -r 4

cd ../evaluation

python3 eval_scannet.py -d <path to *_pred.h5> -p <path to scannet_test.pickle>
```

Please feel free to reopen it if you have other problems~
