### ISSUE TITLE
problem about segmenting the shapenet

### ISSUE THREAD

**Issue by YukioSama** [yangyanli/PointCNN#78]
cant find the tf_sampling_so.so
`NotFoundError: /home/yangll/PointCNN-master/sampling/tf_sampling_so.so: cannot open shared object file: No such file or directory
`

**Comment by burui11087** [comment]
@YukioSama Hi

Have you compiled tf_sampling successfully? This error usually caused by that.

**Comment by YukioSama** [comment]
No，thank you very  much for your reminding!it can be used.

**Comment by YukioSama** [comment]
And I have another question：why is there no files in the models/seg/pointcnn_seg_XXXXXX/ckpts  filefold after executing the train_val_shapenet.sh
thanks!

**Comment by YukioSama** [comment]
sorry,it is caused by the "OOM"
