### ISSUE TITLE
xconv_params and xdconv_params description.

### ISSUE THREAD

**Issue by post2web** [yangyanli/PointCNN#8]
Could someone write a simple explanation of how xconv_params and xdconv_params affect the training?

**Comment by yangyanli** [comment]
Hi @post2web,

We're back from our Chinese New Year vacation, and started to refine the code. We've added some description in the homepage README for explaining these parameters, could you take a look and let us know whether it's clear or not?

**Comment by post2web** [comment]
Thanks, it is a clear description.
