### ISSUE TITLE
Whether the parameter batch_num(/train_val_seg.py) is calculate incorrectly？

### ISSUE THREAD

**Issue by What-ifs** [yangyanli/PointCNN#82]
I find that the parameter num_epochs(/pointcnn_seg/s3dis_x8_2048_fps.py) is 1024,but the parameter num_train(/train_val_seg.py) is calculated by a part training data rather than all training data.

**Comment by What-ifs** [comment]
@burui11087 
I know that it won't influence the performance, but i think that the epoch indeed is not correct rather than expected 1024(/pointcnn_seg/s3dis_x8_2048_fps.py)) if num_train is caculated by a part training data.

**Comment by burui11087** [comment]
yes
