### ISSUE TITLE
About point-cloud subsampling

### ISSUE THREAD

**Issue by AI-Guru** [yangyanli/PointCNN#83]
Namaste!

I your paper you mention a "stress test on small number of input points" and talk about some great results!

I am currently evaluating PointCNN against a use-case of mine: A regression on point-clouds. Predicting the height of measured "objects". 

Currently we have point-clouds with 30k - 38k points. To the best of my knowledge PointCNN delivered great results with point-clouds with maximum size of 2048 points. We would have do downsample. Do you have any ideas/insights about proper downsampling strategies?

Best,
Tristan

**Comment by yangyanli** [comment]
Thanks for your interest, @AI-Guru !

To answer your questions:
1. method for sampling: in most cases, a random sampling should work well, while more advanced sampling methods, such as grid based sampling, or furthest sampling may deliver slightly better results.

2. input size is limited by two factors: GPU memory and KNN search speed. The maximum size of input can be increased to much larger while reducing the batch size to fit in the GPU memory. Also, the larger input size requires much more time on the KNN search (I am not sure whether it has to be real-time in your application?). To resolve the KNN search issue, radius search can be used as an alternative (it would be great if someone can contribute this feature ;-).
