### ISSUE TITLE
Opening up PointCNN

### ISSUE THREAD

**Issue by AI-Guru** [yangyanli/PointCNN#85]
Namaste,

what I really like is the "boxed" approach in your code-base. Just plug in the data, create a settings-scenario and then train. This is excellent for many, many use-cases. Good work!

I wonder: How feasible would it be to open up to a certain degree? I am thinking about making the x-Convolution available as a Keras-layer. This seems to be the most powerful component of the overall approach. And I guess it would make sense to make it highly reusable. This would open the door to many more experiments. Representation learning, triplet-loss, auto-encoders, even GANs to a certain degree.

What do you think?

Best,
Tristan

**Comment by yangyanli** [comment]
Very good suggestions!

However, this is not on our plan, as most of the authors are now working full time in Alibaba. We are working had on keeping this repo well maintained, but won't be able to deliver new features to it, unfortunately...

The further development of PointCNN need more contributions from the community.
