### ISSUE TITLE
segmentation on LIDAR point cloud dataset

### ISSUE THREAD

**Issue by post2web** [yangyanli/PointCNN#9]
Can this architecture be used for segmentation on large areas of LIDAR point clouds? As an example, for the Semantic3D dataset.

**Comment by yangyanli** [comment]
Yes, in almost the same way as that for S3DIS and ScanNet.

We are working on it and got some preliminary results (99+/88% accuracy on training/testing). We will try to address the overfitting, and then release the code for the Semantic3D dataset.

**Comment by post2web** [comment]
I'd really appreciate it if you post the setting parameters and a high level overview of the preprocessing.

**Comment by post2web** [comment]
Thank you for releasing the Semantic3D code and instructions. I followed the steps from README Semantic3D section and executed split_data/semantic3d_split.py but there are no generated h5 files.

I think there is a missing execution of prepare_multiChannel_seg_data.py or prepare_partseg_data.py in the instructions.

**Comment by burui11087** [comment]
Thanks for your report, I have added this command in README.

I'm going to close this issue,if you have another problem, you can reopen an issue.

Thanks
