### ISSUE TITLE
Use extra feature for ModelNet classification

### ISSUE THREAD

**Issue by programmerkiki** [yangyanli/PointCNN#91]
Hi,

We are very grateful to Teacher Li's team for this work. I am so interested in it. And I have several questions during the research process.

When I use modelnet_x3_l4_w_fts.py for train and value for modelnet calssification, it get better result.
Here are some settings:
data_dim = 6
use_extra_features = True
with_normal_feature = True
with_X_transformation = True
Maybe use_extra_features means with_normal_feature?
But input data has only coordinate Information. If I use other extra feature than normal feature, what should I do? 

Thank you in advance!

**Comment by yangyanli** [comment]
use_extra_features means there are input more than x, y, z, it can be normals, or something else.
with_normal_feature means the normals are at the 3,4,5 channels, and they will be rotated during the data augmentation.

**Comment by programmerkiki** [comment]
@yangyanli ，thanks for your kind answer!
May I have more details？
Just for the file modelnet_x3_l4_w_fts.py, use_extra_features = True, what the extra feature is used? Is it normals? 
Where and how the extra feature added in the source code? And how does it work?

Looking forward to your reply！
