### ISSUE TITLE
./train_val_modelnet.sh -g 0 -x modelnet_x3_l4

### ISSUE THREAD

**Issue by chunhuaqiushi1989** [yangyanli/PointCNN#92]
hello ,when I excute the commad:   ./train_val_modelnet.sh -g 0 -x modelnet_x3_l4
it just print "Train/Val with setting modelnet_x3_l4 on GPU 0!",but no any other action,why???

**Comment by yangyanli** [comment]
The training log, as well as tensorboard summary will be written. The folder could be found if you take a look at our homepage ReadMe, or go through the code a bit.

**Comment by RicheyHuang** [comment]
@yangyanli Hello, I met the same problem as the one mentioned above, and no ckpt files can be found in the generated folders. Could you please tell me did I miss some operations before starting training? It just seems like the training doesn't actually start, and the script finishes the whole process within a second.

**Comment by dustindorroh** [comment]
Hi,
Look for the log files. Jobs are backgrounded and redirect stdout and
stderr to a log file based off of the time stamp. In that log file you will
most likely find an error message that may help you further.

Cheers!
Dustin Dorroh

**Comment by RicheyHuang** [comment]
@dustindorroh Thank you very much!

**Comment by yimingyimi** [comment]
表示遇到同样的问题但是找不到日志文件

**Comment by yimingyimi** [comment]
Hello, I met the same problem, but I couldn't find the log file.

**Comment by yimingyimi** [comment]
Hello, I have encountered the same problem but I can't find the log file. I want to know if you have solved the problem.

**Comment by burui11087** [comment]
Hi @yimingyimi 

The generated log file will be stored in _"../../models/seg/"_ or _"../../models/cls/"_ folder with timestamp, that's say the _models_ folder will at same level position with **PointCNN**

**Comment by yimingyimi** [comment]
Thank you. I didn't know why there was no log. TXT before. Now I have the file to shut down the terminal again.Is it the reason for the need for manual parameter adjustment? All the batch_size epochs load_ckpt are None.
![s 1i4yc p tdjb821y yr](https://user-images.githubusercontent.com/43194046/50275072-8e82c700-0479-11e9-9d66-31398e5a76f4.png)
![tp za2sy7kh _fv m55z1s](https://user-images.githubusercontent.com/43194046/50275093-9a6e8900-0479-11e9-8e60-fc776afc52d2.png)

**Comment by yimingyimi** [comment]
Thank you. I still have some mistakes that I don't understand. Perhaps the parameter number?
![rw4yh6oc lr b4ajtp sa96](https://user-images.githubusercontent.com/43194046/50320720-a2293e80-0508-11e9-8549-ec67c4887cea.png)

**Comment by burui11087** [comment]
@yimingyimi 
The output is normal, parameter number is calculated by TF api and 599340 is correct.

**Comment by yimingyimi** [comment]
@burui11087 But he still outputs the following state, and does not see the operation.
![tp za2sy7kh _fv m55z1s](https://user-images.githubusercontent.com/43194046/50324854-4d8fbe80-051c-11e9-92a0-123b9900e2b7.png)

**Comment by burui11087** [comment]
@yimingyimi this output is also normal, the job run in background and you should check the status in log.txt.

**Comment by yimingyimi** [comment]
@burui11087  Perhaps this is the reason, what needs to be changed to make the input and output consistent.
![j z hti4 upspf i62 k](https://user-images.githubusercontent.com/43194046/50331008-2e068f00-0538-11e9-8933-b94430462d10.png)

**Comment by yimingyimi** [comment]
@burui11087 This problem appears in the /home/ym/projects/models/cls/pointcnn_cls_modelnet_x3_l4 file. I don't know how to solve it. Is the problem in the usage of the clip_by_value function?
![j z hti4 upspf i62 k](https://user-images.githubusercontent.com/43194046/50398490-f1929780-07b2-11e9-81ae-0c678baa9382.png)

**Comment by burui11087** [comment]
@yimingyimi 

Please refer to this [link](https://www.tensorflow.org/api_docs/python/tf/clip_by_value). I can run ./train_val_modelnet.sh successfully on TF1.6 and python3.5 just now. Please check your environments and google this error by yourself, because I can't replicate this error.

Thanks

**Comment by burui11087** [comment]
@baoqingfan Hi

We treat "pointcnn_cls_modelnet_x3_l4.txt " as a log.txt. From your posted information, it seems caused by import h5py module, so I think it's better to google this error, there is a reference https://stackoverflow.com/questions/54200850/attributeerror-tuple-object-has-no-attribute-type-upon-importing-tensorflow

**Comment by baoqingfan** [comment]
Thank you very much . According to your method , I solve this problem it can work
Thank you

**Comment by whuhxb** [comment]
Hi @burui11087 

I have also met this error with s3dis, shapenetpart, and modelnet, no output results could be obtained. How to deal with this bug? Thanks a lot.
