### ISSUE TITLE
classification evaluation

### ISSUE THREAD

**Issue by Salingo** [yangyanli/PointCNN#95]
Hi, it seems that there is no test.sh file in folder `./pointcnn_cls`, so how can we evaluate the classification model?
Thanks!

**Comment by burui11087** [comment]
Hi @Salingo 

For classfication task, such as ModelNet40, the validation dataset is the testing dataset, so when we validate it in train_val_cls.py, we can get testing accuracy incidentally.

You you want to evaluate by yourself, please refer to test_general_seg.py file.

Thanks!

**Comment by Salingo** [comment]
OK, thanks for your reply!
