### ISSUE TITLE
My point cloud data only x, y, Z, Intensity values, these four dimensions。 how to train？

### ISSUE THREAD

**Issue by ruanhailiang** [yangyanli/PointCNN#96]
My point cloud data only x, y, Z, Intensity values, these four dimensions。 how to train？

**Comment by ruanhailiang** [comment]
R, G, B are set to 0 values, OK?

**Comment by burui11087** [comment]
hi @ruanhailiang 

Thanks for your interest in our work. If you want to train your own data with intensity values, you can input it as (batch_size,points_num,4) and data looks like (x,y,z,intensity). So it means you do not need to set R,G,B values.

In the setting file, you should set "data_dim = 4, use_extra_features = True, with_normal_feature = False ".

Thanks again.

**Comment by ruanhailiang** [comment]
I'll give it a try. Thank you very much for your prompt reply.

**Comment by xiaomao19970819** [comment]
老哥，你应该是用来跑ccf那个比赛的吧，成功了吗？
