### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by ruanhailiang** [yangyanli/PointCNN#97]
When I test the semantic3d data set, my computer has 64GB of memory. Memory Error appears when I prepare data and train. How much memory does it need?

**Comment by TSchattschneider** [comment]
Are you sure that it's not the graphical memory that you're running out of?
Pasting the error message would be helpful, but my first guess would be that you need to decrease the batch size in `semantic3d_x4_2048_fps.py` to prevent running out of graphical memory while processing batches.

**Comment by ruanhailiang** [comment]
/home/oscar/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
PID: 4369
Namespace(filelist='/home/emg/softcode/data/semantic3d/train_val_files.txt', filelist_val='/home/emg/softcode/data/semantic3d/test_files.txt', load_ckpt=None, model='pointcnn_seg', save_folder='/home/emg/softcode/data/semantic3d/models/seg', setting='semantic3d_x4_2048_fps')
2018-11-03 14:29:21.021460-Preparing datasets...
Traceback (most recent call last):
  File "/home/oscar/softcode/PointCNN-master/train_val_seg.py", line 299, in <module>
    main()
  File "/home/oscar/softcode/PointCNN-master/train_val_seg.py", line 75, in main
    data_val, _, data_num_val, label_val, _ = data_utils.load_seg(args.filelist_val)
  File "/home/oscar/softcode/PointCNN-master/data_utils.py", line 183, in load_seg
    np.concatenate(labels_seg, axis=0),
MemoryError

**Comment by ruanhailiang** [comment]
/home/oscar/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
PID: 4369
Namespace(filelist='/home/emg/softcode/data/semantic3d/train_val_files.txt', filelist_val='/home/oscar/softcode/data/semantic3d/test_files.txt', load_ckpt=None, model='pointcnn_seg', save_folder='/home/oscar/softcode/data/semantic3d/models/seg', setting='semantic3d_x4_2048_fps')
2018-11-03 14:29:21.021460-Preparing datasets...
Traceback (most recent call last):
  File "/home/oscar/softcode/PointCNN-master/train_val_seg.py", line 299, in <module>
    main()
  File "/home/oscar/softcode/PointCNN-master/train_val_seg.py", line 75, in main
    data_val, _, data_num_val, label_val, _ = data_utils.load_seg(args.filelist_val)
  File "/home/oscar/softcode/PointCNN-master/data_utils.py", line 183, in load_seg
    np.concatenate(labels_seg, axis=0),
MemoryError

**Comment by ruanhailiang** [comment]
/home/oscar/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
PID: 4369
Namespace(filelist='/home/oscar/softcode/data/semantic3d/train_val_files.txt', filelist_val='/home/oscar/softcode/data/semantic3d/test_files.txt', load_ckpt=None, model='pointcnn_seg', save_folder='/home/oscar/softcode/data/semantic3d/models/seg', setting='semantic3d_x4_2048_fps')
2018-11-03 14:29:21.021460-Preparing datasets...
Traceback (most recent call last):
  File "/home/oscar/softcode/PointCNN-master/train_val_seg.py", line 299, in <module>
    main()
  File "/home/oscar/softcode/PointCNN-master/train_val_seg.py", line 75, in main
    data_val, _, data_num_val, label_val, _ = data_utils.load_seg(args.filelist_val)
  File "/home/oscar/softcode/PointCNN-master/data_utils.py", line 183, in load_seg
    np.concatenate(labels_seg, axis=0),
MemoryError

**Comment by ruanhailiang** [comment]
My arguments:
-t /home/oscar/softcode/data/semantic3d/train_val_files.txt -v /home/oscar/softcode/data/semantic3d/test_files.txt -s /home/oscar/softcode/data/semantic3d/models/seg -m pointcnn_seg -x semantic3d_x4_2048_fps
GPU: 1080Ti  11GB
memory: 64GB
batch_size = 4   

Test_files.txt
./test/birdfountain_station1_xyz_intensity_rgb_zero_3.h5
./test/stgallencathedral_station6_intensity_rgb_zero_2.h5
./test/marketplacefeldkirch_station1_intensity_rgb_half_1.h5
./test/castleblatten_station5_xyz_intensity_rgb_zero_0.h5
./test/stgallencathedral_station1_intensity_rgb_zero_2.h5
./test/castleblatten_station1_intensity_rgb_half_2.h5
./test/marketplacefeldkirch_station1_intensity_rgb_zero_0.h5
./test/castleblatten_station5_xyz_intensity_rgb_half_3.h5
./test/marketplacefeldkirch_station7_intensity_rgb_half_2.h5
./test/marketplacefeldkirch_station4_intensity_rgb_zero_0.h5
./test/marketplacefeldkirch_station1_intensity_rgb_zero_1.h5
./test/marketplacefeldkirch_station1_intensity_rgb_half_2.h5
./test/castleblatten_station5_xyz_intensity_rgb_half_0.h5
./test/marketplacefeldkirch_station4_intensity_rgb_half_0.h5
./test/marketplacefeldkirch_station7_intensity_rgb_zero_1.h5
./test/castleblatten_station5_xyz_intensity_rgb_zero_2.h5
./test/stgallencathedral_station3_intensity_rgb_zero_2.h5
./test/castleblatten_station1_intensity_rgb_half_3.h5
./test/stgallencathedral_station1_intensity_rgb_zero_0.h5
./test/birdfountain_station1_xyz_intensity_rgb_zero_1.h5
./test/castleblatten_station5_xyz_intensity_rgb_zero_3.h5
./test/birdfountain_station1_xyz_intensity_rgb_half_0.h5
./test/marketplacefeldkirch_station7_intensity_rgb_half_1.h5
./test/castleblatten_station1_intensity_rgb_zero_0.h5
./test/stgallencathedral_station6_intensity_rgb_half_2.h5
./test/stgallencathedral_station3_intensity_rgb_half_2.h5
./test/stgallencathedral_station6_intensity_rgb_half_1.h5
./test/marketplacefeldkirch_station4_intensity_rgb_zero_1.h5
./test/stgallencathedral_station6_intensity_rgb_zero_1.h5
./test/marketplacefeldkirch_station1_intensity_rgb_zero_2.h5
./test/castleblatten_station1_intensity_rgb_zero_2.h5
./test/marketplacefeldkirch_station1_intensity_rgb_half_0.h5
./test/stgallencathedral_station3_intensity_rgb_half_1.h5
./test/birdfountain_station1_xyz_intensity_rgb_zero_2.h5
./test/stgallencathedral_station1_intensity_rgb_half_2.h5
./test/castleblatten_station5_xyz_intensity_rgb_half_4.h5
./test/marketplacefeldkirch_station7_intensity_rgb_half_0.h5
./test/castleblatten_station5_xyz_intensity_rgb_zero_4.h5
./test/marketplacefeldkirch_station4_intensity_rgb_half_1.h5
./test/castleblatten_station5_xyz_intensity_rgb_half_1.h5
./test/stgallencathedral_station3_intensity_rgb_zero_0.h5
./test/birdfountain_station1_xyz_intensity_rgb_half_1.h5
./test/marketplacefeldkirch_station7_intensity_rgb_zero_2.h5
./test/castleblatten_station1_intensity_rgb_half_1.h5
./test/castleblatten_station1_intensity_rgb_zero_1.h5
./test/birdfountain_station1_xyz_intensity_rgb_half_2.h5
./test/stgallencathedral_station1_intensity_rgb_zero_1.h5
./test/birdfountain_station1_xyz_intensity_rgb_zero_0.h5
./test/birdfountain_station1_xyz_intensity_rgb_half_3.h5
./test/stgallencathedral_station3_intensity_rgb_half_0.h5
./test/stgallencathedral_station6_intensity_rgb_zero_0.h5
./test/stgallencathedral_station1_intensity_rgb_half_0.h5
./test/stgallencathedral_station1_intensity_rgb_half_1.h5
./test/castleblatten_station1_intensity_rgb_half_0.h5
./test/castleblatten_station5_xyz_intensity_rgb_zero_1.h5
./test/stgallencathedral_station6_intensity_rgb_half_0.h5
./test/marketplacefeldkirch_station7_intensity_rgb_zero_0.h5
./test/stgallencathedral_station3_intensity_rgb_zero_1.h5
./test/castleblatten_station5_xyz_intensity_rgb_half_2.h5

**Comment by ruanhailiang** [comment]
this code: data_val, _, data_num_val, label_val, _ = data_utils.load_seg(args.filelist_val)  
I understand that it will load all the test data into memory. I am not sure whether it is reasonable or not？

**Comment by TSchattschneider** [comment]
Okay then disregard my initial advice regarding the batch size. I thought you were getting a out of memory error by tensorflow during training.

You could of course try cutting some of the files in the Test_files.txt, reducing the size of the data that is loaded into memory. That should work.
Naturally, decreasing the test set size could come at the price of obtaining less accurate estimates for your models performance.

**Comment by ruanhailiang** [comment]
thanks.

**Comment by burui11087** [comment]
Hi @ruanhailiang 

If your memory can not load all testing .h5 files, you can split it to several small parts and test them separately. Our machine has 512 GB memory so we didn't occur this problem.

BTW, @TSchattschneider  thanks for your help :)

Thanks you all again!

**Comment by yimingyimi** [comment]
Hello, I want to know how much memory you are training on the machine memory, what is used, is the server? If you can run it locally, I use the past deepin system 100G, is there a problem?

**Comment by yimingyimi** [comment]
Hello, I want to know how much memory you are training on the machine memory, what is used, is the server? If you can run it locally, I use the deepin system 100G, is there a problem?

**Comment by burui11087** [comment]
We use DGX server which has 512GB memory. I think your machine should have 256GB memory as least.
