### ISSUE TITLE
partseg

### ISSUE THREAD

**Issue by meteorshowers** [yangyanli/PointCNN#98]
Each testing point cloud is sampled multliple times to make sure all the points are evaluated at least r (r = 10 in our experiments) times at testing time.
what it means in your paper
It seems that it is different from the pointnet?
Thanks a lot!

**Comment by burui11087** [comment]
Hi @meteorshowers 

When we test the the segmentation datasets, we repeat every point tested time and select highest confidence in these results to reduce the instability, and then to get a higher accuracy compared with a single repeat experiment. This trick is used in many networks, such as SSCN(FAIR). 

Thanks!

**Comment by meteorshowers** [comment]
@burui11087  I means that is a object has 10000 points, do you inference 2048 points  every time, until all 10000 points are test 10 times, than you random sample 2048 points to evaluate the miou.
Thanks a lot!

**Comment by burui11087** [comment]
we will test all(2800) points 10 times to get final result, and then, we use all points to calculate miou rather than 2048

**Comment by meteorshowers** [comment]
Tanks a lot！
