### ISSUE TITLE
classification accuracy

### ISSUE THREAD

**Issue by jialancong** [yangyanli/PointCNN#99]
Hi, 
I run ./train_val_modelnet.sh -g 0 -x modelnet_x3_l4 then I got the log.txt：(last two lines)
2018-11-06 11:58:42.213172-[Val  ]-Average:      Loss: 0.3046  T-1 Acc: 0.9153  T-1 mAcc: 0.8782
2018-11-06 11:58:42.875714-Done!

However,in your paper,the accuracy shows in Table 1 is 88.8%(mA) and 92.5%(OA) for Pre-aligned data.
How can I get the same accuracy as in your paper？

Thanks~！

**Comment by burui11087** [comment]
Hi @jialancong 

If you want to get same accuracy of pre-aligned reported in our paper, modelnet_x3_l4_aligned.py is recommended other than modelnet_x3_l4. By the way, I want to know that whether you modify any hyper parameters in these files.

Thanks!

**Comment by jialancong** [comment]
Hi @burui11087 

Thanks for your prompt reply. I am trying modelnet_x3_l4_aligned.py and waiting for the results now. 
As for the settings of the previous results, I just followed PointCNN Usage in README.md and didn't change any hyper parameters. The difference is that I downloaded the ModelNet40 using url in your code by myself.

Thanks~!

**Comment by jialancong** [comment]
Hi,
I run ./train_val_modelnet.sh -g 2 -x modelnet_x3_l4_aligned then I got the log.txt：(last two lines)

2018-11-08 08:47:39.831731-Checkpoint saved to ../../models/cls/pointcnn_cls_modelnet_x3_l4_aligned_2018-11-07-16-42-17_1807/ckpts/iter!
2018-11-08 08:47:44.914915-[Val  ]-Average:      Loss: 0.3455  T-1 Acc: 0.9238  T-1 mAcc: 0.8856
2018-11-08 08:47:45.539313-Done!

The accuracy is improved but still slightly lower than 92.5%. 

Thanks！

**Comment by yangyanli** [comment]
Hi @jialancong，

The model is evaluated multiple times during the train/val session, and the accuracies may be a bit different from different validation iterations.

Could you grep Val or use tensorboard to see the performance from more validation iterations?

**Comment by jialancong** [comment]
Hi @yangyanli ,
Thank you for your reply！I will do more tests.
